### ISSUE TITLE
Unable to open in iOS

### ISSUE THREAD

**Issue by yathit** [crazecoder/open_file#1]
Work fine in Android, but does not open any file iOS (either in Simulator or Actual device).

Console warning

```
[VERBOSE-2:engine.cc(157)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(116)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(398)] Could not launch engine with configuration.
```

**Comment by crazecoder** [comment]
Please confirm the correct version
Please see the detailed https://pub.dartlang.org/packages/open_file#-analysis-tab-

**Comment by yathit** [comment]
Yes version 1.0.5 (Flutter Flutter 0.5.8-pre.195) confirm  and not work in both Simulator and iOS.

BTW, did that work in your example app?

**Comment by crazecoder** [comment]
yes,it worked in iOS Simulator

**Comment by yathit** [comment]
I am not able to run the example due to

```
Running "flutter packages get" in dartsugar...
The current Dart SDK version is 2.0.0-dev.69.5.flutter-8bad5c7b29.

Because dartsugar depends on open_file from path which requires SDK version >=2.0.0 <3.0.0, version solving failed.
pub get failed (1)
```

It is very strange indeed.

**Comment by yathit** [comment]
I have tested your example with dart version fixed https://github.com/yathit/open_file Same error message here.

**Comment by yathit** [comment]
Posted issue in https://github.com/flutter/flutter/issues/20146

**Comment by crazecoder** [comment]
sorry,I forgot to submit the 1.0.5 code to github,you can update and try it

**Comment by crazecoder** [comment]
@yathit is it worked?

**Comment by yathit** [comment]
@crazecoder I have disable for now.

**Comment by crazecoder** [comment]
ok,If you want to use it later and get in trouble, you can @me

**Comment by yathit** [comment]
Actually I want to use now if work.
