### ISSUE TITLE
华为m2  android:5.1.1 打开APK失败

### ISSUE THREAD

**Issue by jisx** [crazecoder/open_file#100]
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            String packageName = context.getPackageName();
            Uri uri = FileProvider.getUriForFile(context, packageName + ".fileProvider", new File(filePath));
            intent.setDataAndType(uri, typeString);
        } else {
            intent.setDataAndType(Uri.fromFile(file), typeString);
        }`

修改 Build.VERSION.SDK_INT > Build.VERSION_CODES.M

**Comment by WilliamCabreira** [comment]
Some problem here with android 5.1
![Anotação 2020-06-29 142835](https://user-images.githubusercontent.com/53832976/86036889-edcd7a00-ba14-11ea-9f55-652eed53f2e3.png)

**Comment by zombieSlicer** [comment]
Same problem here

**Comment by yutianjiaowaimai** [comment]
> Some problem here with android 5.1
> ![Anotação 2020-06-29 142835](https://user-images.githubusercontent.com/53832976/86036889-edcd7a00-ba14-11ea-9f55-652eed53f2e3.png)

load the code as you dependence  ，replace the example wiht you project，then add "open_file:
    path: ../open_file" to you flutter pubspec.yaml, modify the  dependence Android code" if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) " ,problem will be sovled

**Comment by yutianjiaowaimai** [comment]
> Same problem here

load the code as you dependence  ，replace the example with you project，then add "open_file:
    path: ../open_file" to you flutter pubspec.yaml, modify the  dependence Android code" if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) " ,problem will be sovled
