### ISSUE TITLE
Adding multiple file providers in Android application

### ISSUE THREAD

**Issue by intradept** [crazecoder/open_file#104]
`<provider`
`            android:name="androidx.core.content.FileProvider"`
`            android:authorities="${applicationId}.com.shekarmudaliyar.social_share;"`
`            android:exported="false"`
`            tools:replace="android:authorities"`
`            android:grantUriPermissions="true">`
`            <meta-data`
`                android:name="android.support.FILE_PROVIDER_PATHS"`
`                tools:replace="android:resource"`
`                android:resource="@xml/filepaths" />`
`        </provider>`

my app has its own file provider, how do I add your plugin's file provider?

` <provider` 
`                 android:name="androidx.core.content.FileProvider"` 
`                 android:authorities="${applicationId}.fileProvider"` 
`                 android:exported="false"` 
`                 android:grantUriPermissions="true"` 
`                 tools:replace="android:authorities">` 
`             <meta-data` 
`                     android:name="android.support.FILE_PROVIDER_PATHS"` 
 `                    android:resource="@xml/filepaths"` 
`                     tools:replace="android:resource" />` 
 `        </provider>`

**Comment by Susheelkaram** [comment]
Create a custom public class extending `androidx.core.content.FileProvider` and use it for ` android:name`  like this:
```
import androidx.core.content.FileProvider;

public class MyFileProvider extends FileProvider {

}
```
and use it for provider instead of `androidx.core.content.FileProvider` :

```
        <provider
            android:name=".MyFileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource" />
        </provider>
```

This should work.

**Comment by crazecoder** [comment]
5964e2b11a40943998d1a51cd6efa5eb453b7329
