### ISSUE TITLE
I/flutter ( 4433): the /assets/res/file.pdf file is not exists

### ISSUE THREAD

**Issue by Tiebo** [crazecoder/open_file#11]
Hi there, 

I try to open a file with your package and when I try to print the `_result` I get the following error:
`I/flutter ( 4433): the /assets/res/dutyplan.pdf file is not exists`

I importet your package using `import 'package:open_file/open_file.dart';`
and I made sure to specify the PDF file in my pubspec.yaml 
`flutter:
  assets:
    - assets/res/dutyplan.pdf`

Do you have any ideas whats going wrong? Thanks in advance. 
Below you find the code I'm using, which was copied from the example and modified. 
Same error when I try to open a .csv or .txt file.

```
  void loadPDF() {
    openFile('/assets/res/dutyplan.pdf').then((_result) {
      print(_result);
    });
  }

  Future<String> openFile(filePath) async {
    return await OpenFile.open(filePath);
  }
```

**Comment by crazecoder** [comment]
Wrong path, you need to know the real path of android's assets directory in memory or sd card

**Comment by geisher09** [comment]
I get the same error. openFile only works for me with the files within the phone's storage but not in my project's assets. I updated the full path of the file in pubspec.yaml
[`flutter: assets: - assets/files/samplefile.pdf`] 
and it still won't work. But with Flutterpdfviewer, the assets load properly. Can you show me the correct way of accessing(don't know if this is the right term lol) files in my project's assets so openFile could work? Thank you in advance!

**Comment by crazecoder** [comment]
Please refer to the file path from

https://github.com/crazecoder/dilidili/blob/master/lib/db/db_helper.dart
