### ISSUE TITLE
Not working in Android 6.0 using version 3.0.2 and latest 3.0.3

### ISSUE THREAD

**Issue by supermnemonic** [crazecoder/open_file#111]
Produce:
- use open_file version 3.0.2 or 3.0.3
- try to open local file pdf

Result:
- failed to open document viewer (in my case gdrive).
- screen seems to animate to pdf opener app, but suddenly pop back to app.
- this also happen to other types of document (doc, xls, etc).

Expectation:
- can open and show pdf.

Note:
- **it was worked using version 3.0.1**

Environment:
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
Additional: **Mobile device with Android 6.0**

**Comment by crazecoder** [comment]
On my device, I can open PDF files normally. Can you see the error message in logcat?

**Comment by supermnemonic** [comment]
no error message. no logs.

**Comment by oom-** [comment]
Same, is there a way to check that the opening fail ? on my case absolutly nothing happend

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/blob/f9e9acde2a4cb3b3ee2d9cd1840f8fbf1b864abd/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L144-L149

```java
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            ...
}	            
```
@oom- This may be the problem, but I am not sure, you can try to change it, if the problem is solved, I will update it

**Comment by luisms89** [comment]
Hi! We have the same problem in phones with Android 6. We get no errors when debuging, it just not open. However, the users with Android 6 getn an error that says something like: "The document cannot be open because is corrupt".

**Comment by diegogigy** [comment]
same issue here :( cant open pdf in Android 6 and 5 (Samsung and Motorola)... any update for this? thanks!

**Comment by AMuellerAtAHS** [comment]
android 5.1.1
type=ResultType.done and message=done
opens pdf app for a second but then closes automatically

**Comment by ertong** [comment]
In my case it started to work after I set file permission +Xr for the file to be opened.

**Comment by Spooky12** [comment]
> android 5.1.1
> type=ResultType.done and message=done
> opens pdf app for a second but then closes automatically
> 
> Update
> the problem seems to be the temporary directory, i fixed it by using:
> await getExternalStorageDirectories(type: StorageDirectory.documents);
> instead

Using `getExternalStorageDirectories(type: StorageDirectory.documents)` works fine on Android 5 & Android 6

On Android 5 and 6, I can't open PDF stored in directories provided by `getTemporaryDirectory()` or `getApplicationDocumentsDirectory()` but I can open PDF stored in directories provided by `getExternalCacheDirectories()` or `getExternalStorageDirectories()`.

Additionally, on some Android 6 devices if you open PDF with "Drive PDF Viewer" you may need to grant Storage permission to "Drive" app if it was not already granted.

**Comment by crazecoder** [comment]
duplicate of https://github.com/crazecoder/open_file/issues/85

**Comment by Endma** [comment]
Additional info

In my current project, I'm copying a sqlite DB into ApplicationDocumentsDirectory and it works fine. I have read access to it (as I don't need to modify it). This works with Android 10 and with Android 4 kitkat.
So it locks like the problem exists for older Android Versions not granting execution rights to files in ApplicationDocumentsDirectory.
