### ISSUE TITLE
安卓5.1版本无法打开提示报错8.1的版本可以

### ISSUE THREAD

**Issue by xjn19940305** [crazecoder/open_file#114]
安卓5.1的版本打开文件一直报No APP found to open this file。8.1的版本可以正常打开。是不支持低版本的吗，我确定我的APK下载到了本地 并且点进去是可以打开安装的，但是用openfile在安卓5.1的版本下无法打开

**Comment by crazecoder** [comment]
除了apk，其他文件格式打开正常吗

**Comment by xjn19940305** [comment]
> 除了apk，其他文件格式打开正常吗
其他没有试过哦,只试APK。因为我们要实现个自动更新打开APK更新的。是不是5.1和 8.1之间打开的原生API有变化啊？

**Comment by xjn19940305** [comment]
> 除了apk，其他文件格式打开正常吗

    try {
            activity.startActivity(intent);
        } catch (ActivityNotFoundException e) {
            type = -1;
            message = "No APP found to open this file。";
        } catch (Exception e) {
            type = -4;
            message = "File opened incorrectly。";
        }
看起来是启动窗体的时候报的这个错。所以不知道安卓5.1要怎么处理我试过7.1 8.1都可以

**Comment by crazecoder** [comment]
是不是混用了其他插件，我尽量去重现你这个问题

**Comment by xjn19940305** [comment]
我把open_file改成install_apk_plugin这个插件就都可以了。我也不知道为什么这个openfile不支持低版本啊。不过你说的也有道理可能是插件冲突了。因为项目里用的插件比较多，不太好确认
