### ISSUE TITLE
Support for KML and GPX

### ISSUE THREAD

**Issue by S-Man42** [crazecoder/open_file#116]
Is it possible to add explicit support for 

**KML**
* https://en.wikipedia.org/wiki/Keyhole_Markup_Language
* MIME: `application/vnd.google-earth.kml+xml`
* Google Maps, but also other map apps (Android Locus)

**GPX**
* https://en.wikipedia.org/wiki/GPS_Exchange_Format
* MIME: `application/gpx+xml`
* GPS related apps, like map apps (Locus) or Geocaching apps (Android: c:geo, iOS: Cachly)

If not, is it possible to add a function for custom types?

**Comment by crazecoder** [comment]
like this
```dart
OpenFile.open("/sdcard/example.txt", type: "text/plain", uti: "public.plain-text");
```

**Comment by MLThal** [comment]
Thank you for your reply. We already tried this. Unfortunately this didn't work as expected. I guess because of the "public.plain-text" part, it just opened a text editor, not the related map or gpx apps. Could we change it to be more precise and address the related map apps or gps consuming apps?

**Comment by S-Man42** [comment]
Thank you for your reply. We already tried this. Unfortunately this didn't work as expected. I guess because of the "public.plain-text" part, it just opened a text editor, not the related map or gpx apps. Could we change it to be more precise and address the related map apps or gps consuming apps?

**Comment by crazecoder** [comment]
d7e1c500731393bde7c8bb12f28221ceb1da0c6d It is supported on Android, Please let me know if there are any problems

**Comment by Piotr-Wosinek** [comment]
KML and GPX are also supported on ios?
