### ISSUE TITLE
Extra permission

### ISSUE THREAD

**Issue by sm2017** [crazecoder/open_file#120]
Here we have some default permissions https://github.com/crazecoder/open_file/blob/master/android/src/main/AndroidManifest.xml#L5-L6

1. How can I remove them?
2. Why we have `REQUEST_INSTALL_PACKAGES`?
3. I am always using [getApplicationDocumentsDirectory](https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationDocumentsDirectory.html) so I think `READ_EXTERNAL_STORAGE` is redundant , right?

**Comment by crazecoder** [comment]
For ease of use, the required permissions are written in the plugin. If you don't need them, you can remove them using the following methods
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="xxxxx">
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"
        tools:node="remove"/> 
</manifest>
```

**Comment by micsan13br** [comment]
These permissions should not be included by default and moved to the readme page.
"Don't unnecessarily request storage-related permissions for devices that run Android 10 or higher"
https://developer.android.com/training/data-storage/shared/media

**Comment by micsan13br** [comment]
Same goes for "requestLegacyExternalStorage"

`Starting May 5th, you must let us know why your app requires broad storage access with content saying We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.`

**Comment by crazecoder** [comment]
@micsan13br It has been removed in 3.2.0

**Comment by jamesncl** [comment]
@crazecoder I'm using 3.2.1 and I still get this warning in Play Console now:

![image](https://user-images.githubusercontent.com/15979056/190438466-1c0ba8ff-9c7f-44ac-ba12-a55cf0fac503.png)

I think because it is still referenced in code in `OpenFilePlugin.java`:

```
@RequiresApi(api = Build.VERSION_CODES.M)
    private void openApkFile() {
        if (!canInstallApk()) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                startInstallPermissionSettingActivity();
            } else {
                ActivityCompat.requestPermissions(activity,
                        new String[]{Manifest.permission.REQUEST_INSTALL_PACKAGES}, REQUEST_CODE);
            }
        } else {
            startActivity();
        }
    }
```

**Comment by jamesncl** [comment]
> For ease of use, the required permissions are written in the plugin. If you don't need them, you can remove them like this
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:tools="http://schemas.android.com/tools"
>     package="xxxxx">
> <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"
>         tools:node="remove"/> 
> </manifest>
> ```

This doesn't work for me - I have this in my manifest, and now I'm blocked from updating my app because the permission is still there:

![image](https://user-images.githubusercontent.com/15979056/198873857-d08662d4-11c8-48c7-9032-7d933709a958.png)
