### ISSUE TITLE
 Couldn't find meta-data for provider with authority

### ISSUE THREAD

**Issue by diegopereira99** [crazecoder/open_file#124]
I'm getting this error in release mode

`E/flutter ( 6130): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Couldn't find meta-data for provider with authority com.transdesk.transdesk.fileProvider.com.crazecoder.openfile, null, java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.transdesk.transdesk.fileProvider.com.crazecoder.openfile
E/flutter ( 6130):      at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/flutter ( 6130):      at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/flutter ( 6130):      at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/flutter ( 6130):      at com.crazecoder.openfile.OpenFilePlugin.startActivity(OpenFilePlugin.java:147)
E/flutter ( 6130):      at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:107)
E/flutter ( 6130):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 6130):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 6130):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 6130):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6130):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter ( 6130):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter ( 6130): )
E/flutter ( 6130): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter ( 6130): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter ( 6130): <asynchronous suspension>
E/flutter ( 6130): #2      OpenFile.open (package:open_file/src/plaform/open_file.dart:34)
E/flutter ( 6130): <asynchronous suspension>
E/flutter ( 6130): #3      FileContainer._downloadAndOpenFile (package:transdesk/app/modules/client/widgets/file_container.dart:150)
E/flutter ( 6130): <asynchronous suspension>
E/flutter ( 6130):`

**Comment by swarup13** [comment]
java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.merchant.restaurants.dineorder.app.fileProvider.com.crazecoder.openfile 

same error
