### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by DavBfr** [crazecoder/open_file#130]
Will you migrate to sound null safety?

The only dependency you have: [ffi](https://pub.dev/packages/ffi/versions/0.3.0-nullsafety.1) supports it.
Do you need help for that?

**Comment by pinpong** [comment]
Hi, any updates here?

**Comment by nilsreichardt** [comment]
Here are some helpful resources:
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by orevial** [comment]
Just opened a PR on this topic #138 🙂
