### ISSUE TITLE
Does Not Support CSV file Opener

### ISSUE THREAD

**Issue by AhmadRehan71** [crazecoder/open_file#131]
Please support for CSV file opener.

**Comment by crazecoder** [comment]
d7e1c500731393bde7c8bb12f28221ceb1da0c6d It is supported on Android

**Comment by erperejildo** [comment]
> [d7e1c50](https://github.com/crazecoder/open_file/commit/d7e1c500731393bde7c8bb12f28221ceb1da0c6d) It is supported on Android

please, can you provide how to open csv? https://github.com/crazecoder/open_file/issues/164
