### ISSUE TITLE
open_file not work in android release . 

### ISSUE THREAD

**Issue by abdulrehmananwar** [crazecoder/open_file#132]
open file not work in android build release. its work in debug mode. how to resolve this issue

**Comment by kendall-lu** [comment]
getting the same issue

**Comment by mdeveracoding** [comment]
same issue here.

**Comment by brunodmn** [comment]
same here!

**Comment by crazecoder** [comment]
So has brunodmn's approach solve the problem?

**Comment by crazecoder** [comment]
I will close this issue. If this problem still exists in the latest version, please inform me and I will reopen it
