### ISSUE TITLE
The prefix "tools" for attribute "tools:replace" associated with an element type "meta-data" is not bound.

### ISSUE THREAD

**Issue by cntoss** [crazecoder/open_file#135]
unable to build due to above error. code under manifest 

    <provider
              android:name="androidx.core.content.FileProvider"
              android:authorities="${applicationId}.fileProvider"
              android:exported="false"
              android:grantUriPermissions="true"
              tools:replace="android:authorities">
          <meta-data
                  android:name="android.support.FILE_PROVIDER_PATHS"
                  android:resource="@xml/filepaths"
                  tools:replace="android:resource" />
      </provider>

**Comment by crazecoder** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools">
...
</manifest>
```
