### ISSUE TITLE
Support flutter 2.0

### ISSUE THREAD

**Issue by HZRZCW** [crazecoder/open_file#139]
Please Support flutter 2.0!

**Comment by nipunasudha** [comment]
Sad to see dead repositories like this when trying to migrate to Flutter 2.0. Hope the owner will respond soon.

**Comment by psrcek** [comment]
What's the status?? You closed this with no explanation. Does that mean you fully support it now or that you never will?

**Comment by nipunasudha** [comment]
Yeah why did you close @crazecoder

**Comment by crazecoder** [comment]
I think Flutter2.0 is already supported in the latest version, and if it doesn't work, I'll reopen it
