### ISSUE TITLE
requestLegacyExternalStorage permission warning in google play console for android11+

### ISSUE THREAD

**Issue by sumnercreations** [crazecoder/open_file#143]
We are seeing a notification in our google play console that we are using `requestLegacyExternalStorage` permission. After chasing this down we found that it is a dependency of [alice](https://github.com/jhomlala/alice/blob/master/pubspec.yaml) which we use in our application. Is there a plan to update to use a less high risk or sensitive permission? If not is there an explanation for why that permission must be used that we can submit as part of our app submission so that it's not removed from the play store?

![google-legacy-permission-warning](https://user-images.githubusercontent.com/691647/114949419-3b816a80-9e0e-11eb-9d02-321d247b2a63.png)

google answer for reference: https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by dmohler20** [comment]
Yes I received the same warning the other day and tracked it down to this dependency as well.  Any plans on updating?  If not we will have to come up with another option.

**Comment by crazecoder** [comment]
a9f7f54e10130637ccff5e626c643ec87e5b29a4

**Comment by DhavalRKansara** [comment]
Please remove it requestLegacyExternalStorage from your example too.
