### ISSUE TITLE
Filename with spaces would not open in macos

### ISSUE THREAD

**Issue by mludovico** [crazecoder/open_file#144]
When I try to open a file with a space in its name it would not open. I've been able to track down the problem in the macos implementation that is not aware and escaping the space in the system call. I will send a PR with a suggestion. The same would happen to linux.

**Comment by mx1up** [comment]
see !127 , maybe also just use the process class?

**Comment by mludovico** [comment]
@mx1up you're right. I've completely missed that. That would be better than creating a parser like #145 . Are you using it directly in your code or using the tweaked plugin?
Thanks for the heads up!

**Comment by mx1up** [comment]
my PR got merged but I guess @crazecoder thought it was safer to offer the Process route only as an option. So yes, I use the official version with the Process option enabled. 

IMHO, I'm convinced every desktop environment on linux has the xdg-utils dependency (xdg-open command available), so I would just standardize on xdg-open and leave out the native system call route. You could argue though that the Process route requires spawning an extra process which impacts performance. Personally I think it's negligible.

I am not familiar with the macos environment, does it have the xdg-open command? A [quick search](https://superuser.com/a/913226/773138) reveals it would just be called "open". maybe you can verify.

**Comment by mludovico** [comment]
Because I was looking only for a MacOS solution I've ignored what did happen in linux call. It seems ok to me to create a new process specially on Mac because ```open``` is detachable. In a really quick google about xdg-open it is a blocking process. I don't know if there is some sort of arg to make it behave differently. So I really believe that the calls both for mac and linux could be using ```Process.runSync``` with the only difference being the actual command which will be ```open``` and ```xdg-open``` for mac and linux respectively. Apparently runSync method handles spaces and other things on its args parameter.
