### ISSUE TITLE
Openning PDF in iOS

### ISSUE THREAD

**Issue by djireland** [crazecoder/open_file#147]
I'm trying  to open a PDF file that is local to the device on IOS 12. The PDF doesn't open but rather an action dialog box opens (attached) instead. Can we open the PDF directly ?

Here is the code I'm using:

```
     OpenFile.open(report.path,  type: "application/pdf", uti: "com.adobe.pdf");
 ```

and pubspec.yaml

```
 open_file: ^3.2.1
 ```

Thanks!

![Simulator Screen Shot - iPhone 12 - 2021-05-21 at 13 56 46](https://user-images.githubusercontent.com/42627785/119079957-8cebcd80-ba3c-11eb-88ed-dfcc56ba9c1c.png)

**Comment by webnickell** [comment]
I have same issue

**Comment by Allyanora** [comment]
I'm having the same issue for any kind of file on iOS, not just pdf. 

Android also opens this dialog to choose with what program to open and after selection and then the files are opened as expected.

**Comment by crazecoder** [comment]
If you are using a simulator, try it on a real machine

**Comment by webnickell** [comment]
> If you are using a simulator, try it on a real machine

Oh no, we check it on different real IOS devices, this problem is not in simulator.

**Comment by crazecoder** [comment]
I've tried it and it works, Make sure your PDF files are in the app's sandbox, Maybe that's the reason

**Comment by ygotthilf** [comment]
I have the same issue.

I found out the issue happens when the file extension is not '.pdf' even if Uti and Type are set. 

I can reproduce the issue by using  the flutter_cache_manager library that add a .file extension by default.

Hope it helps.

**Comment by ygotthilf** [comment]
The workaround I found for the old ".file" files still in cache looks like:

`  String path = file.path;

    if (path.endsWith('.file')) {
      final copied = await file.copy(
        path.replaceFirst(RegExp(r'\.file$'), '.pdf'),
      );

      path = copied.path;
    }

    await OpenFile.open(
      path,
      type:  'application/pdf',
      uti:  'com.adobe.pdf',
    );`
