### ISSUE TITLE
Cant open any file from cache

### ISSUE THREAD

**Issue by Elendiar** [crazecoder/open_file#148]
From path: /data/user/0/com.xxxx.xxxxx/cache/libCachedImageData/[any-file]
dont opens. Images say that media not found, apk installer says wrong syntax. If i change to another folder, etc /sdcard/Download - it opens. But i need from cache...
Android 6 emulator. result: done, ResultType.done

Or reason of it that another program (gallery or android installer) cant access this folder?

**Comment by hasanalpzengin** [comment]
I can approve this behavior also with new version.

**Comment by PINHOf** [comment]
Same here. The following piece of code works great in Android Emulator, but not on Android Device:
```
final directory = await getTemporaryDirectory();
final path = directory.path;
final String urlFile = 'https://...';

await Dio()
	  .download(urlFile, path + '/some-file.pdf')
	  .whenComplete(() {
	OpenFile.open(path + '/some-file.pdf');
});
```

**Comment by crazecoder** [comment]
> Same here. The following piece of code works great in Android Emulator, but not on Android Device:
> 
> ```
> final directory = await getTemporaryDirectory();
> final path = directory.path;
> final String urlFile = 'https://...';
> 
> await Dio()
> 	  .download(urlFile, path + '/some-file.pdf')
> 	  .whenComplete(() {
> 	OpenFile.open(path + '/some-file.pdf');
> });
> ```

I ran your code and it worked fine on Android11

**Comment by crazecoder** [comment]
> From path: /data/user/0/com.xxxx.xxxxx/cache/libCachedImageData/[any-file]
> dont opens. Images say that media not found, apk installer says wrong syntax. If i change to another folder, etc /sdcard/Download - it opens. But i need from cache...
> Android 6 emulator. result: done, ResultType.done
> 
> Or reason of it that another program (gallery or android installer) cant access this folder?

I don't think this is an available cache path, it should be like this
```
/Android/data/com.xxxx.xxx/cache
```
