### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0xeb (at offset 273)

### ISSUE THREAD

**Issue by jiaxa** [crazecoder/open_file#15]
when i add in AndroidManifest.xml

   <provider
                android:name="android.support.v4.content.FileProvider"
                android:authorities="${applicationId}.fileProvider"
                android:exported="false"
                android:grantUriPermissions="true"
                tools:replace="android:authorities">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/filepaths"
                    tools:replace="android:resource" />
        </provider>

error in title

I'm true file is UTF-8

when i remove , no error happen;

**Comment by jiaxa** [comment]
`   <provider
                android:name="android.support.v4.content.FileProvider"
                android:authorities="${applicationId}.fileProvider"
                android:exported="false"
                android:grantUriPermissions="true"
                tools:replace="android:authorities">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/filepaths"
                    tools:replace="android:resource" />
        </provider>`

**Comment by crazecoder** [comment]
https://github.com/flutter/flutter/issues/15060
