### ISSUE TITLE
OpenFile.open 请求了权限允许后app闪退

### ISSUE THREAD

**Issue by nayoTT** [crazecoder/open_file#159]
```OpenResult openResult = await OpenFile.open(path + '/' + apkName);```
问题是这样 安装app 需要请求允许安装未知应用的权限 我也使用了 Permission.requestInstallPackages.request() 
去修改权限 但是有一个问题 权限变更会导致app闪退 请问各位有什么好的处理办法吗?

**Comment by crazecoder** [comment]
android 11?

**Comment by nayoTT** [comment]
> android 11?



是的

**Comment by nayoTT** [comment]
我也看了92的问题 但是 怎么解决呢 我不想返回的时候app闪退

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/issues/92 android11机制问题

**Comment by nayoTT** [comment]
抱歉.......有什么好的解决办法吗?

**Comment by crazecoder** [comment]
系统级机制问题，想不出有什么办法能解决

**Comment by nayoTT** [comment]
好吧 = = 多谢
