### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hrxiang** [crazecoder/open_file#160]
java.lang.RuntimeException: Unable to resume activity {com.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setFilterTouchesWhenObscured(boolean)' on a null object reference

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (4 available)

**Comment by mpopolin** [comment]
Any updates on this?
