### ISSUE TITLE
 I can't open a PDF created with the iOS 15.0 simulator in Flutter, and the app crashes.

### ISSUE THREAD

**Issue by xcoinmakers-akiyama** [crazecoder/open_file#167]
The Flutter app crashes with open_file.
PDF can be created, displayed and downloaded normally on the actual Android device.

I changed the iOS 15.0 simulator from iPhone 13 Pro Max to iPhone SE (2nd), restarted Android Studio, and tried flutter clean, but it didn't improve.

### Execution environment
macOS BigSur / Android Studio / Simulator iOS 15.0

### code
【pubspec.yaml】
```
dependencies:
	open_file: ^3.2.1
	pdf: ^3.6.1
```
【main.dart】
```
createPdf{
	final Document pdf = Document();
	pdf.addPage(
	  Page(
			~~~~
		),
	);
	final String dir = (await getApplicationDocumentsDirectory()).path;
	final String path = '$dir/report.pdf';
	final File file = File(path);
	await file.writeAsBytes((await pdf.save()));
	OpenFile.open(path); //　← Flutter app crashes here
}
```

**Comment by shofizone** [comment]
I am facing the same issue, But with the video file.

**Comment by jprobert** [comment]
Same issue

**Comment by JulianBissekkou** [comment]
Any solution to this?

**Comment by c2webstudio** [comment]
Same issue here

**Comment by jeromeDms** [comment]
Same issue (only in debug mode), is there a solution ?

**Comment by Matishock1** [comment]
any solution for this?

**Comment by BLACKCAT25896** [comment]
same issue

**Comment by bahag-roostap** [comment]
is this package still maintained? because I see no response or any activity for this issue :-(

**Comment by dubemezeagwu** [comment]
same issue as well. works perfectly fine on android though but crashes on ios

**Comment by Angel1404** [comment]
Mismo problema, alguien le encontro solucion?

**Comment by crazecoder** [comment]
Because it is too old, if the new version still has this problem, please let me know
