### ISSUE TITLE
Update of the Documentation regarding Desktop support

### ISSUE THREAD

**Issue by jlnrrg** [crazecoder/open_file#171]
I noticed the issues and PRs regarding desktop support (especial linux) in this repo.

As I have yet to implement a working `OpenFile.open` for Linux (Ubuntu 20.04.3 LTS) an update of the Documentation would be very much appreciated.

Also the [pub.dev](https://pub.dev/packages/open_file) only lists android and ios as supported. This is confusing, given that `OpenFile.open` has `linuxDeesktopName` and `linuxByProcess` parameters.

**Comment by abulka** [comment]
Is `Mac` and `Windows` supported?  Would be nice to have.
