### ISSUE TITLE
[LayoutConstraints] Unable to simultaneously satisfy constraints error

### ISSUE THREAD

**Issue by premtemp1** [crazecoder/open_file#173]
String path =
 await PdfBuilder.save(await pdf, getFileName());
OpenFile.open(path);
getting the error on click:

Reloaded 1 of 1940 libraries in 334ms.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want.
	Try this:
		(1) look at each constraint and try to figure out which you don't expect;
		(2) find the code that added the unwanted constraint or constraints and fix it.
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint:0x283b1d5e0 h=-&- v=--& UINavigationBar:0x10476f540.minY == 0   (active, names: '|':UILayoutContainerView:0x1047df690 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x283b1fbb0 h=-&- v=--& UINavigationBar:0x10476f540.height == 44   (active)>",
    "<NSLayoutConstraint:0x283b19d10 V:[UINavigationBar:0x10476f540]-(0)-[UIFocusContainerGuide:0x282775ef0'UINavigationControllerContentFocusContainerGuide']   (active)>",
    "<NSLayoutConstraint:0x283b1b890 UIFocusContainerGuide:0x282775ef0'UINavigationControllerContentFocusContainerGuide'.bottom == UILayoutContainerView:0x1047df690.bottom   (active)>",
    "<NSLayoutConstraint:0x283b1b610 V:|-(0)-[UILayoutContainerView:0x1047df690]   (active, names: QLPreviewControllerView:0x11d6513f0, '|':QLPreviewControllerView:0x11d6513f0 )>",
    "<NSLayoutConstraint:0x283b1a440 V:[UILayoutContainerView:0x1047df690]-(0)-|   (active, names: QLPreviewControllerView:0x11d6513f0, '|':QLPreviewControllerView:0x11d6513f0 )>",
    "<NSLayoutConstraint:0x283b1f2a0 'UIView-Encapsulated-Layout-Height' QLPreviewControllerView.height == 0   (active, names: QLPreviewControllerView:0x11d6513f0 )>"
)
Will attempt to recover by breaking constraint

**Comment by tneils218** [comment]
+1 any update

**Comment by crazecoder** [comment]
maybe fixed in last version

**Comment by WeiJun0507** [comment]
I still encountered this error on iOS 18

**Comment by crazecoder** [comment]
This looks like an internal error in UIDocumentInteractionController. It is just a warning. We have not received any feedback that it causes functional problems. We will consider using QLPreviewController in the future.

**Comment by WeiJun0507** [comment]
> This looks like an internal error in UIDocumentInteractionController. It is just a warning. We have not received any feedback that it causes functional problems. We will consider using QLPreviewController in the future.

You may try to load a file on iOS 18 and most likely the file preview is only able to view but cant be dismissed because of missing the height constraint. Wish to get the update of QLPreviewController soon.
