### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method open_file on channel open_file)

### ISSUE THREAD

**Issue by xmy1231** [crazecoder/open_file#175]
![image](https://user-images.githubusercontent.com/10206252/148509903-5d2f1d9b-a5bf-419f-b444-21f38d310067.png)
如图所示，无法打开下载的文件。

**Comment by Kylian21** [comment]
Got the same problem and rebuild the app (not just restart) works for me.

**Comment by SrijanNeoSoftware** [comment]
I'm facing the same problem, flutter clean and rebuilding the app did not work.

**Comment by r3ddev1l** [comment]
I'm facing the same problem, flutter clean and rebuilding the app did not work.

**Comment by SerpentDash** [comment]
Same here... Seriously, this is the only plugin that allows opening files and it doesn't work at all...

**Comment by iShi0n** [comment]
same

**Comment by iShi0n** [comment]
I removed FlutterDownloader, and now it works.

It appears to be a conflict with the file provider.

**Comment by quanghuy-comply** [comment]
I tried FlutterDownloader to download the file, then openfile to view it. But these 2 packages don't work together
