### ISSUE TITLE
Remove usage of jCenter

### ISSUE THREAD

**Issue by ayadlaaouissi** [crazecoder/open_file#178]
🐛 Bug Report
This library still uses jCenter. jCenter doesn't get any updates anymore and should therefor be switched to mavenCentral.

See also https://developer.android.com/studio/build/jcenter-migration

Expected behavior
No dependencies on jCenter

Platform:
🤖 Android

**Comment by MathiasCochet** [comment]
I created a PR for this issue @crazecoder @ayadlaaouissi https://github.com/crazecoder/open_file/pull/184
