### ISSUE TITLE
下载后的apk文件解析软件包时出现问题

### ISSUE THREAD

**Issue by qijunxin** [crazecoder/open_file#18]
使用flutter_downloader成功下载apk文件到本地目录/storage/emulated/0/Download
选择使用软件包安装程序打开时，显示解析软件包时出现问题

androidmanifest.xml配置如下
```
<provider
      android:name="android.support.v4.content.FileProvider"
      android:authorities="${applicationId}.fileProvider"
      android:exported="false"
      android:grantUriPermissions="true"
      tools:replace="android:authorities">
      <meta-data
         android:name="android.support.FILE_PROVIDER_PATHS"
         android:resource="@xml/provider_paths"
         tools:replace="android:resource" />
</provider>
```
provider_paths.xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>
```

**Comment by crazecoder** [comment]
首先确定apk包有没有问题，建议先在文件管理器里找到apk点击安装试试，然后确定apk所在路径是否正确

**Comment by shimingzhishang** [comment]
我也遇到了，apk文件不要放在CacheDirectorye 换到SD卡 ExternalStorageDirectory 就好了。

**Comment by siberiawolf** [comment]
我保存到位置就是ExternalStorageDirectory目录，但是打开之后，依然提示`软件包解析问题`

```
final directory = await getExternalStorageDirectory();
    String _localPath = directory.path;
    final taskId = await FlutterDownloader.enqueue(
      url: 'http://www.ionic.wang/jdshop.apk',
      savedDir: _localPath,
      showNotification:
          true, // show download progress in status bar (for Android)
      openFileFromNotification:
          true, // click on notification to open downloaded file (for Android)
    );
    FlutterDownloader.registerCallback(downloadCallback);
    // 打开文件
    OpenFile.open('${_localPath}/jdshop.apk');
```

开启调试后，显示到调试信息。
```
DownloadWorker{url=http://www.ionic.wang/jdshop.apk,filename=null,savedDir=/storage/emulated/0/Android/data/com.example.flutter_study/files,header=,isResume=false
D/DownloadWorker( 7918): Update notification: {notificationId: 1, title: http://www.ionic.wang/jdshop.apk, status: 2, progress: 0}
D/DownloadWorker( 7918): Open connection to http://www.ionic.wang/jdshop.apk
D/DownloadWorker( 7918): Content-Type = application/octet-stream
D/DownloadWorker( 7918): Content-Length = 3142878
D/DownloadWorker( 7918): Charset = null
D/DownloadWorker( 7918): Content-Disposition = null
D/DownloadWorker( 7918): fileName = jdshop.apk
```

**Comment by crazecoder** [comment]
> 我保存到位置就是ExternalStorageDirectory目录，但是打开之后，依然提示`软件包解析问题`
> 
> ```
> final directory = await getExternalStorageDirectory();
>     String _localPath = directory.path;
>     final taskId = await FlutterDownloader.enqueue(
>       url: 'http://www.ionic.wang/jdshop.apk',
>       savedDir: _localPath,
>       showNotification:
>           true, // show download progress in status bar (for Android)
>       openFileFromNotification:
>           true, // click on notification to open downloaded file (for Android)
>     );
>     FlutterDownloader.registerCallback(downloadCallback);
>     // 打开文件
>     OpenFile.open('${_localPath}/jdshop.apk');
> ```
> 
> 开启调试后，显示到调试信息。
> 
> ```
> DownloadWorker{url=http://www.ionic.wang/jdshop.apk,filename=null,savedDir=/storage/emulated/0/Android/data/com.example.flutter_study/files,header=,isResume=false
> D/DownloadWorker( 7918): Update notification: {notificationId: 1, title: http://www.ionic.wang/jdshop.apk, status: 2, progress: 0}
> D/DownloadWorker( 7918): Open connection to http://www.ionic.wang/jdshop.apk
> D/DownloadWorker( 7918): Content-Type = application/octet-stream
> D/DownloadWorker( 7918): Content-Length = 3142878
> D/DownloadWorker( 7918): Charset = null
> D/DownloadWorker( 7918): Content-Disposition = null
> D/DownloadWorker( 7918): fileName = jdshop.apk
> ```

确认2点
1、是否是android10以上设备（存储机制变更）
2、是否是真实路径

**Comment by Turing-bei** [comment]
有没有解决呢，我也出现了这个问题？

**Comment by crazecoder** [comment]
本issue时间跨度过长，现在关闭，如果新版本还存在此问题，请提交新的issue
