### ISSUE TITLE
Write examples for tests

### ISSUE THREAD

**Issue by ValentinVignal** [crazecoder/open_file#181]
Is it possible to include test on this package so we can have examples on how to write tests with it?

**Comment by burhanrashid52** [comment]
I think having an API where the target platform is checked by the `BuildContext` will help to replace the variant in testing using `variant:` param in `testWidget`. More [here](https://medium.com/geekculture/using-platform-variants-when-testing-flutter-widgets-d3a750d452f0)

Something like this. `OpenFile.open(context,filePath);`
