### ISSUE TITLE
Issue when try to open .xls/.xlsx files

### ISSUE THREAD

**Issue by nickUka** [crazecoder/open_file#185]
Hello, I don't know if I'm the only one facing this but when I try `OpenFile.open(filePath, uti: 'com.microsoft.excel.xls', type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');` It opens an external app viewer but it doesn't open with the file I required. Can anyone help me?

**Comment by libindstme** [comment]
similar issue.i was trying to open a csv formatted file

**Comment by nickUka** [comment]
Turns out, to open the file correctly, it must be on the aplications' directory. I used path_provider and now it works!

**Comment by nickUka** [comment]
Turns out, to open the file correctly, it must be on the aplications' directory. I used path_provider and now it works!
