### ISSUE TITLE
google play rejected my app

### ISSUE THREAD

**Issue by ningning21** [crazecoder/open_file#195]
they saied I can't depend on a plugin which contains code to download or install applications from unknown sources outside of Google Play.  I think this scheme code "application/vnd.android.package-archive" is the trouble

**Comment by Ajay9o9** [comment]
Is this fixed

**Comment by tranvanphay** [comment]
> they saied I can't depend on a plugin which contains code to download or install applications from unknown sources outside of Google Play. I think this scheme code "application/vnd.android.package-archive" is the trouble

Did you has another solution? This library is using Tencent TBS SDK so it will rejected by Google Play?
