### ISSUE TITLE
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1559)] Check failed: fml::jni::CheckException(env).

### ISSUE THREAD

**Issue by chamile** [crazecoder/open_file#199]
I get the following error and the app crashes when calling 

`await OpenFile.open(filePATH);` in Android

![image](https://user-images.githubusercontent.com/12965257/176210914-111f6e64-4227-49ab-aaa4-3a91268eac86.png)
![image](https://user-images.githubusercontent.com/12965257/176210817-7f324237-bc3e-4c7c-a173-769a509a7f27.png)

**Comment by crazecoder** [comment]
Because it is too old, if the new version still has this problem, please let me know
