### ISSUE TITLE
conversion to androidX

### ISSUE THREAD

**Issue by blaneyneil** [crazecoder/open_file#20]
the newest build of flutter migrates to androidX.  i needed to do this:

//import android.support.v4.content.FileProvider;
import androidx.core.content.FileProvider;

//import android.support.v4.app.ActivityCompat;
import androidx.core.app.ActivityCompat;

//import android.support.v4.content.ContextCompat;
import androidx.core.content.ContextCompat;

//import android.support.v4.content.PermissionChecker;
import androidx.core.content.PermissionChecker;

to get this to build.

**Comment by crazecoder** [comment]
androidx try this
```yaml
open_file:
    git:
      url: git://github.com/crazecoder/open_file.git
      ref: androidx
```

**Comment by blaneyneil** [comment]
getting this:

* What went wrong:
Execution failed for task ':app:preDevDebugBuild'.
> Android dependency 'androidx.versionedparcelable:versionedparcelable' has different version for the compile (1.0.0) and runtime (1.1.0-alpha01) classpath. You should manually set the same version via DependencyResolution

but unfortunately can't tell where that's coming from.  unless that rings a bell to you, i'll do some process of elimination later today.

**Comment by crazecoder** [comment]
```grade
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.versionedparcelable'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "1.1.0-alpha01"
            }
        }
    }
}
```
I'm not sure this is going to work, u can try it

**Comment by clairtonluz** [comment]
When this update will be publish in https://pub.dartlang.org/packages/open_file?

**Comment by l-k22** [comment]
I was trying to avoid migrating to AndroidX but open_file ^1.1.1 throws this error. I looked at the change log and there is no mention of anything related to AndroidX

**Comment by crazecoder** [comment]
androidx will push pub later, now use github ref

**Comment by TssT16** [comment]
path_provider and open_file together are not wokring

**Comment by QB3L** [comment]
Using the androidx branch didn't seem to help either for me.

**Comment by khushhalLatif** [comment]
My code is working for Android 9.
But when I tried to open PDF file in Samsung J7 (Api level 22)

Then It shows  "Cannot Display abc.pdf"

**Comment by crazecoder** [comment]
@khushhalLatif That may be the tip of the third party app

**Comment by hoangnguyendn** [comment]
You should make version of Android X to 2.x.x to avoid package auto update like flutter team.

**Comment by vicgrad** [comment]
Indeed, as per recommendations ([here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)) the major version should have been increased with the migration to androidx.
I think it would be best if there was a version 1.4.0 migrating back to support library with all the crashes fixed, and a 2.0.0 with androidx migration.

**Comment by crazecoder** [comment]
@vicgrad @hoangnguyendn Now it does
```yaml
dependencies:
  #androidx
  open_file: ^2.x.x 
  #support
  #open_file: ^1.3.0
```

**Comment by Eltute11** [comment]
> My code is working for Android 9.
> But when I tried to open PDF file in Samsung J7 (Api level 22)
> 
> Then It shows "Cannot Display abc.pdf"

i have the same issue and same devices

**Comment by lufinkey** [comment]
I believe this is related, but when adding this plugin alongside `cloud_firestore`, I get this error:

```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
AGPBI: {"kind":"error","text":"Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler","sources":[{}],"tool":"D8"}
124 actionable tasks: 10 executed, 114 up-to-date
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.
```
