### ISSUE TITLE
Policy Update from Google Play Store

### ISSUE THREAD

**Issue by Harishwarrior** [crazecoder/open_file#201]
## Google Play Store Policy update issue.

You'll need to complete a declaration soon for apps using REQUEST_INSTALL_PACKAGES
Jul 7, 2022 21:15
We found that your manifest file contains the REQUEST_INSTALL_PACKAGES permission.

Starting September 29, 2022, apps that use this permission will not be able to submit updates for review until they have completed a new sensitive permission declaration.

This declaration will be available in Play Console on August 31, 2022. You'll need to declare which permitted functionality your app provides, tell us about a core feature in your app that uses the permission, and provide a video showing its use.

You must remove this sensitive permission from your manifest if your app does not use the permitted functionalities, or if you no longer use this permission. To learn more, watch this [PolicyBytes video](https://www.youtube.com/watch?v=O0UwUF2DgQc&t=139s).

Do you guys have any suggestion on how to solve this ?

**Comment by Harishwarrior** [comment]
https://stackoverflow.com/questions/59598402/why-flutter-has-android-permission-request-install-packages

This issue is already reported in Stackoverflow long time ago.

**Comment by MagnusJohansson** [comment]
This open_file library is abandoned. 
It was raised as a concern back in 2021, but nothing has been done to address it.
There are two alternatives menttioned here: https://github.com/crazecoder/open_file/issues/174
