### ISSUE TITLE
Several Android users received a security alert on our app telling to uninstall it since we use open_file

### ISSUE THREAD

**Issue by adgeg** [crazecoder/open_file#206]
Hello,

First, thanks for your great job :)
Since one month now, we use your library in production. And it strangely matches with several Android users receiving an alert on their device telling "Potential Security Risk. The application XXX appears to be infected. It is advisable to uninstall it immediately." 

We are trying to contact our users to determine either its an anti-malware app or Google Play itself which provides this feedback. Currently, most of those users seems to have Huawei phones, but someones have Samsung too.

Does someone else already experienced that issue with open_file ?

Thanks a lot

**Comment by lucas404x** [comment]
It's probably because this app needs a dangerous permission to open .apk files. I recommend you check out this comment: https://github.com/crazecoder/open_file/pull/205#issuecomment-1202456945
