### ISSUE TITLE
Update ffi dependency

### ISSUE THREAD

**Issue by chewbaccapush** [crazecoder/open_file#210]
Hi! 

Please update the ffi dependency from version 1.0.0 to latest version :)

**Comment by fzyzcjy** [comment]
+!

**Comment by ethael** [comment]
+1

**Comment by javaherisaber** [comment]
@chewbaccapush @fzyzcjy @ethael 
There is another fork [here](https://pub.dev/packages/open_filex) that updated ffi to 2.0+

**Comment by JamesMcIntosh** [comment]
@crazecoder Can you please publish a new release as this is already in the master branch?

**Comment by RobertHeim** [comment]
The package seems abandoned. Use the fork `open_file_plus`

* pub.dev: https://pub.dev/packages/open_file_plus
* github: https://github.com/joutvhu/open_file_plus

**Comment by JamesMcIntosh** [comment]
@RobertHeim That one is also 15 commits behind this repository too, hopefully they're going to do more work on it and fix some of the issues listed here in the issue tracker
