### ISSUE TITLE
Android 13 tries to open file internally, resulting error

### ISSUE THREAD

**Issue by JCChamo** [crazecoder/open_file#213]
When I try to open a local file `await OpenFile.open(path)`, the phone tries to open the file internally from the Flutter app, so to speak. And it results in an error with message "Unable to perform request". 

If I install an additional app for this type of file (PDF Viewer), when I try to open the file, it prompts the app selector "open with" tab. Then, there is no problem to select the app and open it. The problem is when an user doesn't have a third party app, thus not being able to open the file.

![Screenshot_20220914-114219](https://user-images.githubusercontent.com/37709284/190120808-b15f1aa8-3852-41e0-baf9-abb3c6f0c040.png)

The shortaround would be forcing the device to open the file with an external app (Google Drive PDF Reader for example).

**Comment by vinhbui1** [comment]
the same here

**Comment by crazecoder** [comment]
This is not a problem for this plugin, no one knows if the user has the corresponding app on their phone
