### ISSUE TITLE
Conflict between OPEN_FILE and APPWRITE 8.0.0

### ISSUE THREAD

**Issue by sylvainjack** [crazecoder/open_file#214]
I get a conflict between these two packages. Here is the error I get : 
"Because appwrite >=8.0.0-dev.1 depends on flutter_web_auth_2 ^1.1.2 which depends on flutter_web_auth_2_windows ^1.1.2, appwrite >=8.0.0-dev.1 requires flutter_web_auth_2_windows ^1.1.2.
And because every version of flutter_web_auth_2_windows depends on ffi ^2.0.1, appwrite >=8.0.0-dev.1 requires ffi ^2.0.1.
And because open_file 3.2.1 depends on ffi ^1.0.0 and no versions of open_file match >3.2.1 <4.0.0, appwrite >=8.0.0-dev.1 is incompatible with open_file ^3.2.1.
So, because word_champions depends on both open_file ^3.2.1 and appwrite ^8.0.0, version solving failed."

What can be done to solve this problem ?

**Comment by fmdogan** [comment]
try the updated fork of this package : https://pub.dev/packages/open_filex
