### ISSUE TITLE
Open file is not supported on web

### ISSUE THREAD

**Issue by gauria24** [crazecoder/open_file#220]

**Comment by ciceropablo** [comment]
Any news, about it?

**Comment by AliEasy** [comment]
Any updates?!

**Comment by crazecoder** [comment]
Because of the browser security policy issues, I am looking for other implementation methods

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/commit/35b0d8076f48932b91386ae25b6f895e829bf8af
I'm not sure it's what you want
