### ISSUE TITLE
REQUEST_INSTALL_PACKAGES due google playstore policy

### ISSUE THREAD

**Issue by Boukri** [crazecoder/open_file#222]
I can not post any update for my apps in playstore, please update the package ASAP

**Comment by jamesncl** [comment]
Duplicate of https://github.com/crazecoder/open_file/issues/204 https://github.com/crazecoder/open_file/issues/221 and https://github.com/crazecoder/open_file/issues/174

The most active issue seems to be Duplicate of https://github.com/crazecoder/open_file/issues/204 there is a lot of discussion there, I suggest you check it out.

Please search the issues list before opening a new one!
