### ISSUE TITLE
This file could not be accessed. check your connection or make the file name shorter

### ISSUE THREAD

**Issue by Zeinab-Kouhkan** [crazecoder/open_file#224]
I can not open file from /data/user/0/package_name/app_flutter/1.pdf in **android 6** version.
I get 'This file could not be accessed. check your connection or make the file name shorter' or 'the document path is not valid' error in my phone.

**Comment by SarahGhorbani** [comment]
Same as me!

**Comment by javaherisaber** [comment]
@Zeinab-Kouhkan 
Is this error happening only in `Android 6` or can be traced on newer versions of android also?
Can you provide more info eg. `Video, steps to reproduce, Stack trace`

**Comment by crazecoder** [comment]
Because it is too old, if the new version still has this problem, please let me know
