### ISSUE TITLE
The ffi plugins  needs to be upgraded

### ISSUE THREAD

**Issue by liuzehnhang** [crazecoder/open_file#226]
The ffi plugins  needs to be upgraded

**Comment by zacksleo** [comment]
Please new version to pub.dev @crazecoder

**Comment by briosheje** [comment]
@zacksleo I've solved by using anther package called open_filex, it's a fork of this one but has most of the fixes mentioned in the issues here.

**Comment by czredhat** [comment]
@crazecoder please release a new version based on the master branch. It will solve this issue. Thank you
