### ISSUE TITLE
   await open_file.OpenFile.open(fileLocation); crash

### ISSUE THREAD

**Issue by hc2088** [crazecoder/open_file#228]
Trapped uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]' 
(
	0   CoreFoundation                      0x000000010d44d378 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010c411baf objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d4d4641 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x000000010d4ded66 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
	4   CoreFoundation                      0x000000010d4bfc7f -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 243
	5   CoreFoundation                      0x000000010d44bfaa +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   QuickLookUICore                     0x0000000166f1db45 __49+[QLItem(PreviewInfo) contentTypesToPreviewTypes]_block_invoke + 528
	7   libdispatch.dylib                   0x0000<…>
[Bugly] Fatal signal(6) raised.
[Bugly] Forward signal(6) to the previous handler: 0x0

**Comment by crazecoder** [comment]
Because it is too old, if the new version still has this problem, please let me know
