### ISSUE TITLE
Files are no longer opening once targetSDK was updated to 33. Works when targetSDK is set to 30

### ISSUE THREAD

**Issue by Ajayjyothish** [crazecoder/open_file#239]
I have a feature which downloads pdf files and images to the documents directory and uses open_file to open said downloaded files in the devices default pdf and image viewer. This used to work as intended when targetSDK was set to 30.

But when the targetSDK is raised to 33, the files are no longer being opened.
I'v tried switching back to SDK 30 and it works.

I have also provided the new granular permission in Android 13 ( images, audio, video ), have also verified that the file are indeed being written to the application documents directory.

**Comment by nck974** [comment]
Same issue here, can be reproduced with something like:
```dart
    await OpenFile.open(f.path.toString(),
        type: 'text/csv', uti: 'public.comma-separated-values-text');
```
where path was `/storage/emulated/0/Android/data/<my_app>/files/export-1675720222762.csv`

**Comment by crazecoder** [comment]
3.3.0 will no longer request permissions, if you want to open external storage files, you will need to request them yourself
