### ISSUE TITLE
Permission denied: android.permission.READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by VladlenRnd** [crazecoder/open_file#244]
I am using android 13.

When I try to open the apk file it shows me an access error

`OpenFile.open(pathToFile, type: "application/vnd.android.package-archive");`

**Permission denied: android.permission.READ_EXTERNAL_STORAGE**
How can I open a file?

Flutter doctor
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2728], locale en)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.23)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.77.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by imagination24** [comment]
add `<uses-permission
        android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>` in your AndroidManifest

**Comment by crazecoder** [comment]
3.3.0将不再请求权限，如果你想要打开外部存储文件，你需要自己请求它们
https://developer.android.google.cn/about/versions/13/behavior-changes-13?hl=zh-cn#granular-media-permissions
