### ISSUE TITLE
Why are there two equal startActivity?

### ISSUE THREAD

**Issue by gumulka** [crazecoder/open_file#25]
One here:
https://github.com/crazecoder/open_file/blob/d36e8c3701539ee1d3461b1cda8bc50c063217a5/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L116
and one here:
https://github.com/crazecoder/open_file/blob/d36e8c3701539ee1d3461b1cda8bc50c063217a5/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L139

**Comment by crazecoder** [comment]
sorry, there was something wrong with merge branches, then fix it
and thx reminding me
