### ISSUE TITLE
Can't open file in example: `D/permissions_handler(15381): No permissions found in manifest for: []22`

### ISSUE THREAD

**Issue by nilsreichardt** [crazecoder/open_file#250]
## Description

I'm unable to use the example. When I click the "Tap to open file", I get the following error:

```
D/permissions_handler(15381): No permissions found in manifest for: []22
```

## Steps to reproduce

1. Clone this repository
2. Navigate to the `example`
3. Run `flutter run` for an Android device
4. Click "Try to open file"

## Demo

https://user-images.githubusercontent.com/24459435/234576723-05b1f071-12fa-4696-bfd7-3603a56b0c0d.mov

## Context

Used commit: f19c0363cb9c73f9aa8d76a392d9981c8883491f

**Comment by crazecoder** [comment]
Sorry, Example just test something, Maybe I should remove the debugged code

**Comment by crazecoder** [comment]
0ee6d69
