### ISSUE TITLE
The file cannot be opened and there is no error message

### ISSUE THREAD

**Issue by tanwanlanyue1** [crazecoder/open_file#259]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.19044.3086], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.0)
[√] Android Studio (version 2020.3)
[√] Connected device (5 available)
[√] Network resources

! Doctor found issues in 1 category.

open_file: ^3.3.2，I added everything to the list.xml.

 OpenFile.open('/sdcard/Download/161.jpg'); 
The system did not open the file, and the console did not prompt an error message, but it is OK for me to use the emulator, and my own mobile phone cannot be opened. This is the configuration of the emulator
![image](https://github.com/crazecoder/open_file/assets/50123920/bdb7920d-b680-42f2-ab35-673a5a7aaa20)，
The phone I use is an OnePlus ACE 2v, Android version 13

**Comment by tanwanlanyue1** [comment]
Each call to OpenFile.open('/sdcard/Download/161.jpg'); The console prints the following information
![image](https://github.com/crazecoder/open_file/assets/50123920/8e43e1da-505b-4cd2-bc7a-bcda040251ae)

**Comment by raywoocn** [comment]
same problem here.

**Comment by tanwanlanyue1** [comment]
I changed the plugin and used open_filex. It will prompt that the popup window can be pulled up. You can try it


> 同样的问题在这里。

**Comment by raywoocn** [comment]
> 

What did you modify to make it work?

**Comment by raywoocn** [comment]
> I changed the plugin and used open_filex. It will prompt that the popup window can be pulled up. You can try it


What did you modify to make it work?

**Comment by crazecoder** [comment]
Turning it off now, and if the problem persists with the new version, I'll reopen it
