### ISSUE TITLE
Can we have an EDIT possibility?

### ISSUE THREAD

**Issue by gumulka** [crazecoder/open_file#26]
Maybe a boolean optional argument for open.

This could result in an Intent.ACTION_EDIT instead of Intent.ACTION_VIEW.

**Comment by crazecoder** [comment]
This is not a required feature, and there is no plan to add this attribute in order to ensure the unity of the two platforms

**Comment by gumulka** [comment]
So what does iOS do, when you want to open a .txt file for editing?
Sorry for having absolutely no idea about iOS.
