### ISSUE TITLE
open_file 3.3.2: OpenFilePlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by hosamyousof** [crazecoder/open_file#260]
I got the following error when run on android 

Note: C:\Users\Hosam\AppData\Local\Pub\Cache\hosted\pub.dev\open_file-3.3.2\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by mahdiRoyalSoft** [comment]
i have the same problem did you find the solution

**Comment by JASEEMCP** [comment]
use open_file_plus package instead of open_file package.

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/issues/249#issuecomment-2313202786
