### ISSUE TITLE
Security: fileprovider allow access to all app files

### ISSUE THREAD

**Issue by itzikkle** [crazecoder/open_file#262]
hi,
after apk decompile, i see that the package gives access to all the files under app domain, 
since it uses "."
Since the package add to the assembled manifest access to ALL files under the app, 
It makes a security vulnerability for the app.  
All the files can be accesses by other apps, and its problematic policy. 
The problem, is that in the **file_paths.xml**, the package put “.” (access to all files). 
Can you please add something more restrictive (specific files/directories)? 

**provider android:name="com.crazecoder.openfile.FileProvider" android:exported="false" android:authorities="com.fmr.meitavtradeapp.fileProvider.com.crazecoder.openfile" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/filepaths"/>
**file_paths.xml:** 

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path name="external-path" path="."/>
    <external-cache-path name="external-cache-path" path="."/>
    <external-files-path name="external-files-path" path="."/>
    <files-path name="files_path" path="."/>
    <cache-path name="cache-path" path="."/>
    <root-path name="root" path="."/>
</paths>**

**Comment by crazecoder** [comment]
https://developer.android.google.cn/privacy-and-security/risks/android-exported
```android:exported="false"```
Maybe that's what it's for
