### ISSUE TITLE
Localization issue with iOS modal in open_file package

### ISSUE THREAD

**Issue by aince42** [crazecoder/open_file#263]
When utilizing the open_file package on an iOS device, a localization issue arises. When attempting to open a file devoid of a file extension (e.g., without .png, .jpg, .pdf), a native modal (UIDocumentPickerViewController) is initiated by the iOS system. This modal provides the end user with various interaction options, including saving the file to different directories or cloud services. The issue is that the labels for these interaction options are displayed in English, despite the device's system language being set to German. This suggests a missing or erroneous localization behavior within the package or in its interaction with Apple's frameworks.

**Specific instances:**
The label "Save to Files" should be localized as "In Dateien speichern".
The label "Save to Dropbox" should be localized as "In Dropbox speichern".
The label "Run Script" should be localized as "Script ausführen".

**Expected Behavior:**
Labels and captions within the modal should be correctly localized according to the iOS device's system language.

**Screenshots:**
![IMG_0036](https://github.com/crazecoder/open_file/assets/115079695/6f4c9ea6-a982-42e1-9376-9ac0647fad57)
![IMG_0037](https://github.com/crazecoder/open_file/assets/115079695/88c41d7f-b120-4a89-b3b7-7443c5305c7c)

**Comment by licai28** [comment]
need
