### ISSUE TITLE
A compile warning

### ISSUE THREAD

**Issue by vinxzhu** [crazecoder/open_file#267]
When I compiled it with Flutter 3.13.6 it reported some warnings, can this be fixed?

.pub-cache/hosted/pub.dev/open_file-3.3.2/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java uses or overrides a deprecated API.

<img width="1228" alt="image" src="https://github.com/crazecoder/open_file/assets/4533708/3985c273-455c-4699-8c2c-b0e2662b2626">

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/issues/249#issuecomment-2313202786
