### ISSUE TITLE
Cannot build apk

### ISSUE THREAD

**Issue by dende1234** [crazecoder/open_file#277]
When entering flutter build apk the following error appeared: 
error: package com.crazecoder.openfile does not exist
      flutterEngine.getPlugins().add(new com.crazecoder.openfile.OpenFilePlugin());

I already did flutter upgrade and I only added the dependency
How do I solve this error?

**Comment by grizzlei** [comment]
A clean build (`flutter clean` then `flutter build apk`) should work.

**Comment by crazecoder** [comment]
Is it still in the new version?
