### ISSUE TITLE
resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by liguande** [crazecoder/open_file#28]
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:226: error: resource android:attr/fontVariationSettings not found.
  /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:226: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

请问是啥问题，一天了，实在没办法了。。

**Comment by crazecoder** [comment]
发下app的gradle看看

**Comment by liguande** [comment]
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "cn.ninechapter.beenet"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by liguande** [comment]
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "cn.ninechapter.beenet"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

**Comment by liguande** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "cn.ninechapter.beenet"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by crazecoder** [comment]
改成28

**Comment by liguande** [comment]
我尝试过28，但是又有新的问题
D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/3.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Volumes/macdata/workspace/BeenetApp/build/app/intermediates/transforms/dexBuilder/debug/48.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel$Stub

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by liguande** [comment]
解决了，谢谢
