### ISSUE TITLE
Using outdated API

### ISSUE THREAD

**Issue by lualbertovargas** [crazecoder/open_file#285]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: C:\Users\3.3.2\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by AnasEsh** [comment]
Found a solution?

**Comment by lualbertovargas** [comment]
Not until now

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/issues/249#issuecomment-1586917020
