### ISSUE TITLE
Third-Party Apps Not Opening to Show Downloaded Files on iOS.

### ISSUE THREAD

**Issue by moin-nimblechapps** [crazecoder/open_file#286]
This package successfully opens third-party apps to display downloaded files on Android. However, it does not work as expected on iOS. On iOS, it directly opens the downloaded file in the application rather than presenting a choice of third-party apps to open the file.

**Comment by dhirenapplore** [comment]
i am getting issue in of What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing C:\ships_app\android\app\src\main\AndroidManifest.xml

**Comment by crazecoder** [comment]
This is because ios currently uses DocumentInteraction

**Comment by crazecoder** [comment]
try this on 3.5.3
```dart
OpenFile.open("/sdcard/example.txt", isIOSAppOpen: true);
```
