### ISSUE TITLE
Package open_filex:linux references open_filex:linux as the default plugin, but it does not provide an inline implementation. Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: open_filex` or add an inline implementation to open_filex via `platforms: linux:` `pluginClass` or `dartPluginClass`.

### ISSUE THREAD

**Issue by lucasjinreal** [crazecoder/open_file#289]
Package open_filex:linux references open_filex:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: open_filex`
or add an inline implementation to open_filex via `platforms: linux:` `pluginClass` or `dartPluginClass`.

**Comment by Aruljebaraj** [comment]
any solution to this?

**Comment by KatoValdte2e** [comment]
Hi, any solution?

**Comment by selvam920** [comment]
+1

**Comment by bhavik-mangla** [comment]
Same issue

**Comment by PY-Account** [comment]
same issue

**Comment by sjordan2010** [comment]
Created a pull request to hopefully address this issue. I just removed the platforms from pubspec.yaml... #290

**Comment by rafaelrosadev** [comment]
> maybe you can try 3.5.0

Please upgrade the firebase_core dependency

**Comment by crazecoder** [comment]
> firebase_core

firebase_core is not referenced in this plug-in
