### ISSUE TITLE
下载后的apk ,打开了爱奇艺的客户端，无法正常打开apk安装

### ISSUE THREAD

**Issue by xiaojia21190** [crazecoder/open_file#30]

**Comment by crazecoder** [comment]
提示什么

**Comment by xiaojia21190** [comment]
什么都没提示。直接用爱奇艺播放的文件
![image](https://user-images.githubusercontent.com/16084693/54006223-63b23000-4197-11e9-93cd-35944c3b112d.png)

**Comment by crazecoder** [comment]
```
OpenFile.open("/sdcard/example.txt");
```
不是目录的路径，是文件的路径

**Comment by xiaojia21190** [comment]
打开了apk，但是显示未知应用，无法安装

**Comment by crazecoder** [comment]
把apk放在sd卡的最外层目录试试，可能是文件夹的读取权限的问题

**Comment by xiaojia21190** [comment]
![image](https://user-images.githubusercontent.com/16084693/54009133-a0d0ef00-41a4-11e9-99a4-eb085480c586.png)
能不能直接弹出这个弹窗啊

**Comment by crazecoder** [comment]
8.0以上会跳到设置未知来源安装界面，你的场景是什么版本

**Comment by xiaojia21190** [comment]
8.0的

**Comment by crazecoder** [comment]
那不应该啊

**Comment by shingohu** [comment]
@crazecoder  不能直接跳转到安装未知应用的界面？ 现在跳转到的是外层的应用列表的界面

**Comment by shingohu** [comment]
@RequiresApi(api = Build.VERSION_CODES.O)
    private void startInstallPermissionSettingActivity() {
        Uri packageURI = Uri.parse("package:" + getPackageName());
        //注意这个是8.0新API
        Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageURI);
        startActivityForResult(intent, 10086);
    }
