### ISSUE TITLE
iOS 18 no option to close the mp4 video  

### ISSUE THREAD

**Issue by ATeteryatnikov** [crazecoder/open_file#301]
After updating my device to iOS 18, an error appeared.  
I am opening a video file. The video opens in full screen mode and start play. There are no video control buttons and no close button. 
So it is not possible to go back to the apps.
Is there any suggestion what it could be?

**Comment by crazecoder** [comment]
<img src="https://github.com/user-attachments/assets/39fb7c49-c902-416f-8f24-ac6d9e333b15" width="30%">

I tried it, and didn't encounter this problem

**Comment by ATeteryatnikov** [comment]
Was able to localize the problem on a newly created application by setting values in info.plist. 
UIBackgroundModes: 
- fetch 
- remote-notification 
- audio

**Comment by crazecoder** [comment]
I've done that without any problems
