### ISSUE TITLE
Opening files attributed to the app on Android

### ISSUE THREAD

**Issue by davidd7** [crazecoder/open_file#302]
The newest version of this package (3.5.7) still cannot open all files that it should be able to open without a permission on Android.

Calling OpenFile.open(path) with a path leading to a file created by me in shared storage (e.g., '/storage/emulated/0/Pictures/myfolder/myfile.png') returns ResultType.permissionDenied with the message "Permission denied: android.permission.READ_MEDIA_IMAGES".

However, apps should be able to open such files. This is explained in https://developer.android.com/training/data-storage/shared/media#storage-permission-not-always-needed and https://developer.android.com/training/data-storage/shared/media#app-attribution. Apps are allowed to open files that are attributed to them (i.e., that were created by them) even if they have no permission at all and this is also valid for files placed outside of the app's own directory.

Indeed the image in my code example above opens without a problem if I remove the following condition from your java implementation:

```
if (FileUtil.isImage(mimeType) && !hasPermission(Manifest.permission.READ_MEDIA_IMAGES) && !Environment.isExternalStorageManager()) {
     /*...*/
}
```

Thus this package behaves more restrictedly than what's normal on Android. Unfortunately, I don't know how (if at all) one can check whether a file is attributed to an app before trying to open it.

**Comment by crazecoder** [comment]
Try 3.5.8 to see if it solves your problem

**Comment by davidd7** [comment]
Thank you for your response. Still doesn't work unfortunately, I still get 'Permission denied: android.permission.READ_MEDIA_IMAGES'

**Comment by crazecoder** [comment]
Try this and let me know if it works
```
dependency_overrides:
  open_file_android: ^1.0.5
```

**Comment by crazecoder** [comment]
3.5.9
