### ISSUE TITLE
'keyWindow' is deprecated: first deprecated in iOS 13.0 

### ISSUE THREAD

**Issue by mr-slonn** [crazecoder/open_file#307]
When building for iOS 15, I receive the following notification:

return [UIApplication sharedApplication].keyWindow.rootViewController;
/.pub-cache/hosted/pub.dev/open_filex-4.5.0/ios/Classes/OpenFilePlugin.m:34:46 'keyWindow' is deprecated: first deprecated in iOS 13.0 - Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

**Comment by crazecoder** [comment]
Unfortunately, open_filex is not maintained by me, you can try to contact its maintainer, or change it to open_file

**Comment by Albert221** [comment]
You can fix it with the below right below `<manifest>` in your `AndroidManifest.xml`:

```xml
    <!-- Added by open_filex -->
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" tools:node="remove" />
```

Make sure you also have `xmlns:tools="http://schemas.android.com/tools"` in the `<manifest>`.

The `tools:node="remove"` removes the permission from the resulting manifest.
