### ISSUE TITLE
A function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by mr-slonn** [crazecoder/open_file#308]
When building for iOS 15, I receive the following notification:

static UIViewController *RootViewController() {
/.pub-cache/hosted/pub.dev/open_filex-4.5.0/ios/Classes/OpenFilePlugin.m:10:44 A function declaration without a prototype is deprecated in all versions of C

**Comment by crazecoder** [comment]
duplicate of #307
