### ISSUE TITLE
Remove Photo and video permissions permission or submit declaration on Google Play Console

### ISSUE THREAD

**Issue by nik007frontbit** [crazecoder/open_file#316]
I am using open_filex in one feature and function work fine in android and ios

but when i upload it on the play store it will give an error of 
android.permission.READ_MEDIA_IMAGES
android.permission.READ_MEDIA_VIDEO
declaration

how to solve this ?
becuase with out this package i can not pick and read the files or videos

[https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html]

if i write declaration it will reject by saying this is not the core funtion what to do and that feature is also important in one flow
![WhatsApp Image 2024-12-10 at 15 14 27](https://github.com/user-attachments/assets/8628a23f-3894-487c-be44-88d9c57ecc86)

**Comment by Imgkl** [comment]
@nik007frontbit Found a solution for this?

**Comment by Imgkl** [comment]
@crazecoder 

> Maybe you can contact the forked repo maintainer, or use this repo

Does this mean, by using this package instead of open_filex would solve this issue?
