### ISSUE TITLE
Can't build iOS [as the default plugin, but it does not provide an inline implementation.]

### ISSUE THREAD

**Issue by mumenahmedbright** [crazecoder/open_file#318]
after upgrading flutter to the latest version [3.27.1] I get a warning whenever I run [pub get] I get this message
Package open_app_file:linux references open_app_file:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of open_app_file to either avoid referencing a default implementation via `platforms: linux: default_package: open_app_file` or add an inline implementation to open_app_file via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package open_app_file:macos references open_app_file:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of open_app_file to either avoid referencing a default implementation via `platforms: macos: default_package: open_app_file` or add an inline implementation to open_app_file via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package open_app_file:windows references open_app_file:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of open_app_file to either avoid referencing a default implementation via `platforms: windows: default_package: open_app_file` or add an inline implementation to open_app_file via `platforms: windows:` `pluginClass` or `dartPluginClass`.

additionally I can't build iOS build.

**Comment by crazecoder** [comment]
open_app_file is just a fork library, Maybe you can switch to open_file
