### ISSUE TITLE
更新flutter1.2出错

### ISSUE THREAD

**Issue by liguande** [crazecoder/open_file#32]
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:12: 错误: 程序包android.support.annotation不存在
import android.support.annotation.RequiresApi;                          
                                 ^                                      
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:13: 错误: 程序包android.support.v4.content不存在
import android.support.v4.content.FileProvider;                         
                                 ^                                      
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:14: 错误: 找不到符号
import android.support.v4.app.ActivityCompat;                           
                             ^                                          
  符号:   类 ActivityCompat                                             
  位置: 程序包 android.support.v4.app                                   
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:15: 错误: 程序包android.support.v4.content不存在
import android.support.v4.content.ContextCompat;                        
                                 ^                                      
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:16: 错误: 程序包android.support.v4.content不存在
import android.support.v4.content.PermissionChecker;                    
                                 ^                                      
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:278: 错误: 找不到符号
    @RequiresApi(api = Build.VERSION_CODES.M)                           
     ^                                                                  
  符号:   类 RequiresApi                                                
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:292: 错误: 找不到符号
    @RequiresApi(api = Build.VERSION_CODES.M)                           
     ^                                                                  
  符号:   类 RequiresApi                                                
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:300: 错误: 找不到符号
    @RequiresApi(api = Build.VERSION_CODES.O)                           
     ^                                                                  
  符号:   类 RequiresApi                                                
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:309: 错误: 找不到符号
    @RequiresApi(api = Build.VERSION_CODES.M)                           
     ^                                                                  
  符号:   类 RequiresApi                                                
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:328: 错误: 找不到符号
    @RequiresApi(api = Build.VERSION_CODES.M)                           
     ^                                                                  
  符号:   类 RequiresApi                                                
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:65: 错误: 找不到符号
        return ContextCompat.checkSelfPermission(activity, permission) == PermissionChecker.PERMISSION_GRANTED;
               ^                                                        
  符号:   变量 ContextCompat                                            
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:65: 错误: 找不到符号
        return ContextCompat.checkSelfPermission(activity, permission) == PermissionChecker.PERMISSION_GRANTED;
                                                                          ^
  符号:   变量 PermissionChecker                                        
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:89: 错误: 找不到符号
                    ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, REQUEST_CODE);
                    ^                                                   
  符号:   变量 ActivityCompat                                           
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:129: 错误: 找不到符号
            Uri uri = FileProvider.getUriForFile(context, packageName + ".fileProvider", new File(filePath));
                      ^                                                 
  符号:   变量 FileProvider                                             
  位置: 类 OpenFilePlugin                                               
/Volumes/macdata/data/flutter/.pub-cache/hosted/pub.dartlang.org/open_file-1.3.0/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java:284: 错误: 找不到符号
                ActivityCompat.requestPermissions(activity,             
                ^                                                       
  符号:   变量 ActivityCompat                                           
  位置: 类 OpenFilePlugin                                               
15 个错误                                                               
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':open_file:compileDebugJavaWithJavac'.       
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org   
更新了一下flutter 报错了

**Comment by crazecoder** [comment]
如果你是用androidx，请用2.0.1

**Comment by liguande** [comment]
tks!
