### ISSUE TITLE
Android dependency 'androidx.slidingpanelayout:slidingpanelayout' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by 841660202** [crazecoder/open_file#34]
Android dependency 'androidx.slidingpanelayout:slidingpanelayout' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

![image](https://user-images.githubusercontent.com/18305361/55080977-fdeffe80-50d9-11e9-80bc-98a7513c080c.png)

did:
![image](https://user-images.githubusercontent.com/18305361/55081037-195b0980-50da-11e9-8566-ec46f25532e9.png)

![image](https://user-images.githubusercontent.com/18305361/55081068-24ae3500-50da-11e9-9cf2-9a7ce23a5ed2.png)
![image](https://user-images.githubusercontent.com/18305361/55081118-3b548c00-50da-11e9-8d09-90729a3c689d.png)

**Comment by crazecoder** [comment]
https://github.com/crazecoder/open_file/issues/20

**Comment by 841660202** [comment]
![image](https://user-images.githubusercontent.com/18305361/55084820-8bcee800-50e0-11e9-9524-8bd2bd69a795.png)
![image](https://user-images.githubusercontent.com/18305361/55084904-b28d1e80-50e0-11e9-812f-6f6140256fa5.png)

**Comment by 841660202** [comment]
@crazecoder 怎么解决？#20 没看懂如何解决

**Comment by crazecoder** [comment]
报什么错改成什么，不是照抄。。。

**Comment by ShubhranshuShekhar** [comment]
Try upgrding your gradle
https://github.com/flutter/flutter/issues/27254
