### ISSUE TITLE
Open file from URL

### ISSUE THREAD

**Issue by aleksander351** [crazecoder/open_file#39]
Is it possible, to open a file from a remote url address?

Or do I have to download the file separately to a temp folder?

**Comment by ganisback** [comment]
same requirement for me

**Comment by crazecoder** [comment]
download and open it

**Comment by aleksander351** [comment]
I am using cache manager:
flutter_cache_manager: "^0.3.2"

var file = await DefaultCacheManager().getSingleFile(
                <url-to-file>
              );
OpenFile.open(file.path);

**Comment by xyzbilal** [comment]
> I am using cache manager:
> flutter_cache_manager: "^0.3.2"
> 
> var file = await DefaultCacheManager().getSingleFile(
> 
> );
> OpenFile.open(file.path);
man you saved my life. thanks.
