### ISSUE TITLE
Error on AndroidManifest.xml

### ISSUE THREAD

**Issue by feriyalsusanto** [crazecoder/open_file#4]
Hello, i got error on new version 1.0.7 as the image shown below
![error1](https://user-images.githubusercontent.com/10955932/43948106-168aba14-9cb4-11e8-8ed6-87693b1f3ef3.PNG)

and my pubspec.yaml
![error2](https://user-images.githubusercontent.com/10955932/43948135-2c13478e-9cb4-11e8-9efa-dc7a8db07488.PNG)

On previous version i don't encounter this error, but after upgrade to 1.0.7 and image_picker to 0.4.6 this error show up.

Thanks for the awesome library.

**Comment by crazecoder** [comment]
the readme has given the solution, you can try it

**Comment by feriyalsusanto** [comment]
ahhh i see, i have add it before like in the android folder, but i'm not adding the tools:replace="android:resource".
Thank you so much.
