### ISSUE TITLE
Plugin intercepting permission results from other plugins on android

### ISSUE THREAD

**Issue by andrewackerman** [crazecoder/open_file#40]
I have some native code in my app that requests microphone access. On android, if I accept the pop-up prompt, the app crashes. I traced the cause of the crash to this plugin in the `startActivity` function at the `File file = new File(filePath);`. I believe this is because in the `onRequestPermissionsResult` function, it calls `startActivity` after the processing of the permission result is complete regardless of what the permission was or whether this plugin was the one that requested it. This causes `startActivity` to fire even though `filePath` is still null.

I believe this is related to #31.

**Comment by crazecoder** [comment]
The problem has been solved in 2.0.1+1, Which version do you use

**Comment by paqio** [comment]
Still having the issue

**Comment by crazecoder** [comment]
@paqio Thank you for your feedback. I have tried the issue of regression test, but it did not appear again. So what is your usage scenario and what is the problem

**Comment by paqio** [comment]
i was using camera_utils, which had same FileProvider, for some reason if i set the authority/resources to the one in readme, camra utils would look for its provider hardcoded in the code not fileProvider but flutter.fileprovder and crash. i did use the replace. I ended up using other plugin image_picker which had custom file provider

**Comment by crazecoder** [comment]
@paqio 
```
import android.support.v4.content.FileProvider;
```
camera_utils is support, open_file is androidx.
You can use the support version of open_file, which hasn't been updated for a long time, or tell the developer of camera_utils to migrate to androidx

**Comment by paqio** [comment]
yeah i did that, both(manually converted), so no issuess on build. yet when the camera_utils was looking for getApplicationName() + 'flutter.provider' . it was not in the map, only 'fileProvider' was in the map.

**Comment by crazecoder** [comment]
```dart
Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    openFile(image.path);
 }
```
I tried it with image_picker: ^0.6.0+10, and it worked
This is image_picker
```java
activity.getPackageName() + ".flutter.image_provider";
```
So I think it's a question of camera_utils, You can try getApplicationName() instead of getPackageName()

**Comment by paqio** [comment]
image picker works out of the box, not the camera_utils. But i think its more popular replacement so its good enough solution
