### ISSUE TITLE
No implementation found for method open_file on channel open_file

### ISSUE THREAD

**Issue by Allan-Nava** [crazecoder/open_file#44]
I use the versione without androidX compatible  `#open_file: ^1.3.0`
`MissingPluginException(No implementation found for method open_file on channel open_file)`

**Comment by crazecoder** [comment]
I gave it a try, It worked. And since most plugins are androidx, the support version has not been maintained for a long time, Are you sure you want to use it?

**Comment by crazecoder** [comment]
#48
