### ISSUE TITLE
Bug of opening apk file in huawei mate9

### ISSUE THREAD

**Issue by juncaixinchi** [crazecoder/open_file#45]
在华为mate9手机上使用 open_file打开任何Apk文件，会导致应用自己在桌面的图标消失，我尝试定位了一下问题：

1. 应用管理里还能看到原应用，需要卸载重新安装才能看到原有应用的图标。
2. 该现象发生在安装apk之前，也就是说在跳出安装应用页面和权限验证之前，apk图标就消失了

设备名称：HUAWEI Mate 9
EMUI版本：8.0.0
Android版本：8.0.0

**Comment by juncaixinchi** [comment]
@crazecoder 能看一下这个问题吗？谢谢

**Comment by crazecoder** [comment]
手上没这个机器，而且这个库只是打开apk，图标消失的问题应该是emiui的问题

**Comment by juncaixinchi** [comment]
确实是emui的bug导致的，修改一下AndroidManifest.xml即可

`<action android:name="android.intent.action.VIEW"/> `中不能有 `<data android:mimeType="*/*"/>`这样的通配描述
