### ISSUE TITLE
File not opening after download

### ISSUE THREAD

**Issue by liepaja** [crazecoder/open_file#50]
I am downloading a pdf via http and storing the file in the externalStorageDirectory via path_provider. After calling OpenFile.open on the directory, yet it just a black screen. 
I am able to locate and open the file from file manager. 

Could this be the issue with Android Fileprovider?

**Comment by crazecoder** [comment]
I've tried it and it's ok, this is my code
```dart
    Directory tempDir = await getExternalStorageDirectory();
    String filePath = "${tempDir.path}/flutter-dilidili.apk";
    if(File(filePath).existsSync()){
        File(filePath).deleteSync();
    }
    Dio dio = new Dio();
    Response response = await dio.download("https://raw.githubusercontent.com/crazecoder/dilidili/master/apk/flutter-dilidili.apk", filePath,onReceiveProgress:(_c,_t){
      print(_c/_t*100);
    },);
    final message = await OpenFile.open(filePath);
```

**Comment by liepaja** [comment]
can you also add image_picker? That way we can see if it is the FileProvider. Without the image_picker it works for me as well.

**Comment by crazecoder** [comment]
It still works
```dart
    Directory tempDir = await getExternalStorageDirectory();
    String filePath = "${tempDir.path}/screen.png";
    print(filePath);
    if (File(filePath).existsSync()) {
      File(filePath).deleteSync();
    }
    Dio dio = new Dio();
    Response response = await dio.download(
      "https://raw.githubusercontent.com/crazecoder/dilidili/master/screenshot/screen.png",
      filePath,
      onReceiveProgress: (_c, _t) {
        print(_c / _t * 100);
      },
    );
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);

    filePath = image.path;
    print(filePath);
    final message = await OpenFile.open(filePath);
```

**Comment by liepaja** [comment]
and does it open the image? For me its blank, copied your example

**Comment by crazecoder** [comment]
save path
```
I/flutter ( 7594): /storage/emulated/0/Android/data/com.crazecoder.openfileexample/files/screen.png
```
open path 
```
I/flutter ( 7594): /storage/emulated/0/Android/data/com.crazecoder.openfileexample/files/Pictures/scaled_screen.png
```
I chose the path "/storage/emulated/0/Android/data/com.crazecoder.openfileexample/files/screen.png", but the printed path is not, I'm not sure about the mechanism of image_picker

**Comment by Zeeshan0201** [comment]
> I've tried it and it's ok, this is my code
> 
> ```dart
>     Directory tempDir = await getExternalStorageDirectory();
>     String filePath = "${tempDir.path}/flutter-dilidili.apk";
>     if(File(filePath).existsSync()){
>         File(filePath).deleteSync();
>     }
>     Dio dio = new Dio();
>     Response response = await dio.download("https://raw.githubusercontent.com/crazecoder/dilidili/master/apk/flutter-dilidili.apk", filePath,onReceiveProgress:(_c,_t){
>       print(_c/_t*100);
>     },);
>     final message = await OpenFile.open(filePath);
> ```

@crazecoder getting this error after implementing above method in dio download..
**MissingPluginException(No implementation found for method open_file on channel open_file)
![Screenshot from 2019-08-01 12-02-56](https://user-images.githubusercontent.com/45591301/62270723-52263900-b454-11e9-9db3-82fc050c9001.png)
**

**Comment by crazecoder** [comment]
@Zeeshan0201 #48

**Comment by Zeeshan0201** [comment]
@crazecoder yes it's worked for me! thanks for your quick response :+1:

**Comment by liepaja** [comment]
Hmm, had to reinstall my ubunut, hence new flutter and vscode. Now it works for some reason .Thanks for support
