### ISSUE TITLE
Error message when opening a downloaded file

### ISSUE THREAD

**Issue by fkranenburg** [crazecoder/open_file#51]
I receive the following error message:

`Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference`'

I download a file using [dio](https://pub.dev/packages/dio)  and try to open it using this code flow:
```
Response<dynamic> response = await dio.download(url,downloadFilePath);
      if(response.statusCode == 200){
        OpenFile.open(downloadFilePath);    
      }
```

This is de stacktrace:
`androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
com.crazecoder.openfile.OpenFilePlugin.startActivity(OpenFilePlugin.java:130)
com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:93)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:336)
 android.os.Looper.loop(Looper.java:174)
 android.app.ActivityThread.main(ActivityThread.java:7356)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

How can I fix this?

**Comment by crazecoder** [comment]
https://stackoverflow.com/questions/30896130/fileprovider-crash-npe-attempting-to-invoke-xmlresourceparser-on-a-null-string

**Comment by fkranenburg** [comment]
I fixed it. The problem was that I added the `<provider>` part inside my AndroidManifest.xml as stated in the documentation, but after that it wouldn't compile my project anymore. But this happened because I forgot to add ` xmlns:tools="http://schemas.android.com/tools"` inside the manifest tag... 

Thanks for the help!
