### ISSUE TITLE
How to open (.docx, .xlsx, .pptx) files on iOS?

### ISSUE THREAD

**Issue by RenanDelfanti** [crazecoder/open_file#53]

**Comment by crazecoder** [comment]
```
OpenFile.open("/sdcard/example.txt", type: "text/plain", uti: "public.plain-text");
```
You can find the uti you need here:
https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html#//apple_ref/doc/uid/TP40009259-SW1

**Comment by RenanDelfanti** [comment]
Thanks @crazecoder

**Comment by JamesMcIntosh** [comment]
@crazecoder That document does not have the information about docx, pptx, xlsx. I have tested the XLSX these value which worked successfully. The others are inferred by the naming convention.
```
docx: org.openxmlformats.wordprocessingml.document
pptx: org.openxmlformats.presentationml.presentation
xlsx: org.openxmlformats.spreadsheetml.sheet
```

**Comment by AndroidNils** [comment]
There is the same bug on android. Any solutions for this?

**Comment by JamesMcIntosh** [comment]
@AndroidNils Android just relies on you having an application which knows how to open the corresponding mime type. These are the mime types which the plugin advertises for the following extensions: 

https://github.com/crazecoder/open_file/blob/master/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L191
docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
xslx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation"

The match the ones listed in
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

@AndroidNils have you debugged the `OpenFilePlugin.startActivity()` to make sure everything looks ok for your use case?

**Comment by The-Heyman** [comment]
I think this should have been stated in the docs upfront to save everybody time!
