### ISSUE TITLE
Does nothing for .docx files on Android Emulator

### ISSUE THREAD

**Issue by rfogar2** [crazecoder/open_file#54]
## Issue
Opening a `.docx` file on the Android Emulator does nothing. File is not opened and no error is thrown.

The last related log is
```
2019-08-29 12:08:14.136 1969-2863/system_process I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.pacakge.whatever.fileProvider/cache-path/somefileofmine.docx typ=application/vnd.openxmlformats-officedocument.wordprocessingml.document flg=0x20000001} from uid 10087
```

## Example code
```
File file = File("${tempDir.path}/somefileofmine.docx");
await OpenFile.open(file.path);
```

## Setup
Device: Android Nexus 5X (Emulator)
Target: Android 9.0 (Google APIs)

## EDIT - More Details
Works as expected on physical device (huawei honor 10 lite) and iOS Simulator. 

Could be an issue with android emulator not having an app which can open the .docx file. I think OpenFile should then throw an exception instead of doing nothing.

**Comment by crazecoder** [comment]
```
OpenFile.open("${tempDir.path}/somefileofmine.docx");
```

**Comment by rfogar2** [comment]
> ```
> OpenFile.open("${tempDir.path}/somefileofmine.docx");
> ```

Sorry, I wrote the example code wrong. Updated it to match what I am doing in my repo.
