### ISSUE TITLE
Filter selectable files by multiple file extensions

### ISSUE THREAD

**Issue by whigger85** [crazecoder/open_file#56]
It would be great to define multiple file extensions in combination with the "FileType.CUSTOM" parameter. For instance, if I want the user to be able to select only text and PDF files I can't restrict this using a single file extension.

**Comment by crazecoder** [comment]
I think you can determine the file name before calling the openfile method

**Comment by whigger85** [comment]
Sorry, I've posted T the request in the wrong repository.
