### ISSUE TITLE
Interests in adding go-flutter support?

### ISSUE THREAD

**Issue by jld3103** [crazecoder/open_file#60]
Hi @crazecoder I added support for [go-flutter](https://github.com/go-flutter-desktop/go-flutter) for this plugin: https://github.com/jld3103/go-flutter-open_file.
Do you want to me put my plugin implementation into this repo? That would make the code management easier.

https://github.com/go-flutter-desktop/plugins/pull/29

**Comment by crazecoder** [comment]
The support for pc is just a beta, I just tried it on macos, I am not sure if it can work on windows and linux.

**Comment by jld3103** [comment]
This is a custom implementation for go-flutter. This doesn't work like the implementation for FDE.

**Comment by crazecoder** [comment]
Ok, if it doesn't affect the use of the plugin

**Comment by jld3103** [comment]
No it doesn't. The code needs to be refactored a little bit to fix the imports, but that is not a big task
