### ISSUE TITLE
应用自动升级安装完APK后，没有完成界面，直接返回手机主页面。

### ISSUE THREAD

**Issue by yangxinp** [crazecoder/open_file#61]
在应用里面下载和打开APK后，可以安装程序。但是安装完就瞬间到手机首页了，没有任何提示。预期的效果应该是安装完后，出现会"完成"和"打开"的安装完成界面。

**Comment by didyqian** [comment]
下载了Android App安装文件后，在执行安装时不能显示"完成，打开"界面，这是因为没有为intent设置setFlags(Intent.FLAG_ACTIVITY_NEW_TASK).可以按type修复一下吗？

**Comment by crazecoder** [comment]
这是部分机型问题吗？

**Comment by didyqian** [comment]
> 
> 
> 这是部分机型问题吗？

不是的，所有机型都有这个问题，是代码的问题，这是因为没有为intent设置setFlags(Intent.FLAG_ACTIVITY_NEW_TASK).

**Comment by Iongtao** [comment]
> > 这是部分机型问题吗？
> 
> 不是的，所有机型都有这个问题，是代码的问题，这是因为没有为intent设置setFlags(Intent.FLAG_ACTIVITY_NEW_TASK).

我也遇到了这个问题，安装完成后 点击打开 无法调到app，而是回到了系统首页

**Comment by crazecoder** [comment]
历史遗留问题，现在关闭，如果新版本还存在此问题，请重新提交issue或者@我重新打开
