### ISSUE TITLE
CSV file support on android and ios

### ISSUE THREAD

**Issue by guyzk** [crazecoder/open_file#62]
Is there any chance to add support for .csv files?

https://github.com/crazecoder/open_file/issues/46
In the above issue there is a workaround to open .csv files but it only works if you have ms excel installed. If you want to open the file with google sheets it will say that the file is corrupted when it is not since if you access the same file from any other file explorer or app (whatsapp, telegram etc) it opens up just fine in google sheets.

**Comment by erperejildo** [comment]
why was this closed? I'm facing same issue

**Comment by syawqi** [comment]
I'm facing same issue
