### ISSUE TITLE
Package name conflict

### ISSUE THREAD

**Issue by yuefeng007** [crazecoder/open_file#64]
* What went wrong:

Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute provider#androidx.core.content.FileProvider@authorities value=(com.example.app.fileprovider) from [:flutter_webview_plugin] AndroidManifest.xml:11:13-64

        is also present at [:open_file] AndroidManifest.xml:14:13-64 value=(com.example.app.fileProvider).

        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:9:9-17:20 to override.

**Comment by crazecoder** [comment]
The solution is in readme
