### ISSUE TITLE
could not be loaded because: net::ERR_ACCESS_DENIED

### ISSUE THREAD

**Issue by yairsafe** [crazecoder/open_file#67]
I trying to open local html file (in internal storage) and only in *android Marshmallow* and below (api level 23) and  i get this error:

Webpage not available The webpage at file:///data/user/0/com.example.example/app_flutter/1576506336054.html could not be loaded because: net::ERR_ACCESS_DENIED

In android Nougat (api level 24) and above everything is fine.

I add these uses permission to AndroidManifest.xml File:

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET"/>

Of course i asking storage Permission before i try to read these file.

![Annotation 2019-12-16 163437](https://user-images.githubusercontent.com/31651758/70916967-2c758700-2025-11ea-8888-629d8bce0d40.jpg)

**Comment by crazecoder** [comment]
Is it opened through a webview? If so, maybe you should add 
```
mWebView.getSettings().setAllowFileAccess(true);
```
