### ISSUE TITLE
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)

### ISSUE THREAD

**Issue by Jarvan1997** [crazecoder/open_file#68]
如题 报这个错怎么办？
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)

**Comment by crazecoder** [comment]
试试flutter clean

**Comment by devibrahimkarahan** [comment]
> 试试flutter clean

Worked for me

**Comment by tony123S** [comment]
I tried flutter clean, but still get the error.
