### ISSUE TITLE
Opening camera on image_picker

### ISSUE THREAD

**Issue by vibhav2799** [crazecoder/open_file#7]
I am getting the error below only when I use open_file with image_picker. If I remove open_file from pubspec.yaml, the camera opens normally.

>E/flutter (12347): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (12347): PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)
E/flutter (12347): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter (12347): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (12347): <asynchronous suspension>
E/flutter (12347): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:47:40)
E/flutter (12347): <asynchronous suspension>
E/flutter (12347): #3      UploadFilesToDatasetState.getImage (file:///Users/vibhavkotriwala/Desktop/work/4ceed_app/lib/pages/upload_to_dataset.dart:20:35)
E/flutter (12347): <asynchronous suspension>
E/flutter (12347): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter (12347): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter (12347): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (12347): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (12347): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (12347): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (12347): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (12347): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (12347): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (12347): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (12347): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (12347): #15     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (12347): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

**Comment by crazecoder** [comment]
Because image_picker doesn't take conflict into account, we have to prioritize it,so you can modify like this 

```
     <provider
                android:name="android.support.v4.content.FileProvider"
                android:authorities="${applicationId}.flutter.image_provider"
                android:exported="false"
                android:grantUriPermissions="true"
                tools:replace="android:authorities">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/flutter_image_picker_file_paths"
                    tools:replace="android:resource" />
        </provider>
```

**Comment by vibhav2799** [comment]
Works, thanks.

**Comment by paqio** [comment]
But than you can't use OpenFile right?
