### ISSUE TITLE
Migrate to Android Plugin API v2

### ISSUE THREAD

**Issue by nailgilaziev** [crazecoder/open_file#70]
When using this plugin in flutter module (embedding flutter to a native app) 
pub get throw next warning:
```
The plugin `open_file` is built using an older version of the Android plugin API 
which assumes that it's running in a full-Flutter environment. 
It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following 
https://flutter.dev/go/android-plugin-migration.
```

**Comment by nailgilaziev** [comment]
this message thrown:

1. every time you run app
2. try to build framework by command `flutter build ios-framework --output=../x_embed/`

**Comment by crazecoder** [comment]
319067f57aa293afedc5c55642767538c325768d

**Comment by nailgilaziev** [comment]
cool! 
I will wait stable version to test it out!
When it will be released?
