### ISSUE TITLE
Download image and open works on Android not iOS

### ISSUE THREAD

**Issue by LewPerren** [crazecoder/open_file#71]
Hi,

Thanks for the helpful plugin. I have the following issue on iOS:

Successfully download jpeg file to app directory (using path_provider  getApplicationDocumentsDirectory()). The jpeg is viewable in app in Android and iOS. The jpeg can be successfully opened using external app using open_file in Android. However, in iOS it opens external app, but just shows an image placeholder that says the filename and file type. It should be noted that the iOS info.plist file has been emended to include the following keys as Yes:

UIFileSharingEnabled 

LSSupportsOpeningDocumentsInPlace

Thanks

**Comment by crazecoder** [comment]
I tried it and it worked, This is  my code
```dart
    Dio dio = Dio();
    var dir = await getApplicationDocumentsDirectory();
    var filePath = "${dir.path}-1.jpg";
    await dio.download("http://c.hiphotos.bdimg.com/album/w%3D2048/sign=10ee29e14b90f60304b09b470d2ab21b/10dfa9ec8a136327f8bc67e3908fa0ec09fac789.jpg",filePath);

    final message = await OpenFile.open(filePath);
```

**Comment by LewPerren** [comment]
Thanks for quick response. Did you take any special steps on iOS to make file available, like changes to info.plist.

Thanks

**Comment by crazecoder** [comment]
no, just this

**Comment by LewPerren** [comment]
Thanks again for your help. I will try again with your code, although my implementation is very similar.

**Comment by LewPerren** [comment]
Hi,

I just tried your code and I get the same result on the simulator, please see screen shot:

![Screenshot 2019-12-25 11 11 47](https://user-images.githubusercontent.com/19366322/71444217-86520d00-2707-11ea-94c5-f6c398043d64.png)

**Comment by crazecoder** [comment]
Have you tried other image urls?

**Comment by LewPerren** [comment]
Yes I have tried different images. Interestingly, it I go to the print option of the image it shows preview:

![Screenshot 2019-12-25 11 27 37](https://user-images.githubusercontent.com/19366322/71444506-b26e8d80-2709-11ea-942a-a812110537a1.png)

**Comment by crazecoder** [comment]
That's weird, This is my screenshot
![image](https://user-images.githubusercontent.com/18387906/71453609-03908700-27c7-11ea-804b-ef5a4b4260e4.png)

**Comment by LewPerren** [comment]
Hi,

Thanks for all your help with this issue. I have now been able to try the code on a physical iPad and it worked as expected. It appears to be an issue with the iOS simulator I am using. It may be something to do with my setup or perhaps is worthy of a note in the installation guide. If you would like a note, I am happy to write some amendments for you to merge if you are happy.

Thanks again.

Lew

**Comment by LewPerren** [comment]
Thanks, I have closed the issue as the plugin works great on a real device, it is just an issue with the latest iOS simulator.

Thanks again.

**Comment by juanjoserodrigolazaro** [comment]
hello opening docx or doc not working on ios, tested on android and its fine! with the same dio code.
