### ISSUE TITLE
与flutter_webview_plugin冲突，已经按照ReadMe进行配置，仍然不行

### ISSUE THREAD

**Issue by didyqian** [crazecoder/open_file#72]
AndroidManifest.xml已经加上
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.xxx.xxx">`
`        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource" />
        </provider>`
项目中同时用到了flutter_webview_plugin，在打开相册时闪退。
报错日志：
`W/System.err( 9542): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err( 9542): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
W/System.err( 9542): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err( 9542): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err( 9542): 	at com.flutter_webview_plugin.WebviewManager.getOutputFilename(WebviewManager.java:407)
W/System.err( 9542): 	at com.flutter_webview_plugin.WebviewManager.access$800(WebviewManager.java:51)
W/System.err( 9542): 	at com.flutter_webview_plugin.WebviewManager$5.onShowFileChooser(WebviewManager.java:350)
W/System.err( 9542): 	at com.android.webview.chromium.WebViewContentsClientAdapter.showFileChooser(WebViewContentsClientAdapter.java:1069)
W/System.err( 9542): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.runFileChooser(AwWebContentsDelegateAdapter.java:219)
W/System.err( 9542): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9542): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
W/System.err( 9542): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9542): 	at android.os.Looper.loop(Looper.java:150)
W/System.err( 9542): 	at android.app.ActivityThread.main(ActivityThread.java:5546)
W/System.err( 9542): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9542): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
W/System.err( 9542): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

**Comment by crazecoder** [comment]
flutter_webview_plugin的命名规范问题，我提交了pr，还没有合并，你可以先用我的fork
https://github.com/crazecoder/flutter_webview_plugin
```dart
                              WebviewScaffold(
                                url: _url,
                                providerName: "fileProvider",
                                ...
                              ),
```

**Comment by didyqian** [comment]
> 
> 
> flutter_webview_plugin的命名规范问题，我提交了pr，还没有合并，你可以先用我的fork
> https://github.com/crazecoder/flutter_webview_plugin
> 
> ```dart
>                               WebviewScaffold(
>                                 url: _url,
>                                 providerName: "fileProvider",
>                                 ...
>                               ),
> ```

好的，谢谢
