### ISSUE TITLE
安装APK时，不出现安装完成界面

### ISSUE THREAD

**Issue by didyqian** [crazecoder/open_file#74]
安装APK时，不出现安装完成界面，建议在startActivity方法中增加代码判断是否APK：
`Intent intent = new Intent(Intent.ACTION_VIEW);
        if(TYPE_STRING_APK.equals(typeString))
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        else
        intent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);`

**Comment by crazecoder** [comment]
这个问题是部分机型存在，还是所有机型都存在？

**Comment by xiaojiedeVX** [comment]
部分机型，我用的是三星，然后安卓版本6.0.0
