### ISSUE TITLE
android的路径问题

### ISSUE THREAD

**Issue by zouzhenglu** [crazecoder/open_file#75]
在android用getApplicationDocumentsDirectory的时候，路径会比getExternalStorageDirectory多一个app_flutter，这两个路径有什么区别？
我在用OpenFile这个库的时候，发现用getExternalStorageDirectory的路径能打开系统内置分享，但是getApplicationDocumentsDirectory就失败了。
` Unhandled Exception: PlatformException(error, Failed to find configured root that contains /data/data/com.xxx.xxx/app_flutter/xxx/data_lib/3fa821d8fb4344aa853746b049a8bac0.png, null)`
在file provider中我配置了下面的路径
`
    <external-path name="external_files" path="."/>
    
    <external-path name="beta_external_path" path="Download/"/>
    
    <external-path name="beta_external_files_path" path="Android/data/"/>`

问题1：这两个方法的区别？
问题2：如何配置相关路径才能分享？

**Comment by crazecoder** [comment]
```dart
/// On Android, this uses the `getDataDirectory` API on the context. Consider
/// using [getExternalStorageDirectory] instead if data is intended to be visible
/// to the user.
Future<Directory> getApplicationDocumentsDirectory() async {
  final String path =
      await _channel.invokeMethod<String>('getApplicationDocumentsDirectory');
  if (path == null) {
    return null;
  }
  return Directory(path);
}
```
getDataDirectory()
返回用户数据目录。（从安全性上来说，应该不会允许非系统级应用访问用户数据目录）
```dart
/// On Android this uses the `getExternalFilesDir(null)`.
Future<Directory> getExternalStorageDirectory() async {
  if (_platform.isIOS) {
    throw UnsupportedError('Functionality not available on iOS');
  }
  final String path =
      await _channel.invokeMethod<String>('getStorageDirectory');
  if (path == null) {
    return null;
  }
  return Directory(path);
}
```
getExternalFilesDir(String type)
返回应用程序可以放置其拥有的持久文件的主共享/外部存储设备上目录的绝对路径。
