### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by glennmichaelmejias** [crazecoder/open_file#77]
Ability to open directory and show list of files from file explorer installed on the phone.

**Comment by crazecoder** [comment]
https://github.com/huang-weilong/flutter_file_manager
like this?

**Comment by glennmichaelmejias** [comment]
@crazecoder not exactly, I want to open installed file explorer app like es file explorer etc.

**Comment by crazecoder** [comment]
I see, but I have no idea about this feature, if you have ideas, welcome pr
