### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mamun361054** [crazecoder/open_file#78]
ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method open_file on channel open_file)
E/flutter (26683): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

**Comment by crazecoder** [comment]
flutter clean and try again

**Comment by Mamun361054** [comment]
same error showing

**Comment by Mamun361054** [comment]
![Screenshot 2020-01-13 at 1 13 47 PM](https://user-images.githubusercontent.com/20486372/72238008-aee26e00-3606-11ea-930d-2bde6849891e.png)

**Comment by crazecoder** [comment]
This is a problem that you can usually solve with flutter clean, and if it doesn't, I think you can check your project for other problems

**Comment by shengdoushi** [comment]
flutter clean has no work
`
E/flutter ( 1667): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method open_file on channel open_file)
E/flutter ( 1667): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 1667): <asynchronous suspension>
E/flutter ( 1667): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 1667): #2      OpenFile.open (package:open_file/src/plaform/open_file.dart:34:36)
E/flutter ( 1667): #3      _installApkFile (package:teacherapp/utils/checkUpdate.dart:205:19)
E/flutter ( 1667): #4      _onAPKDownloadCallback (package:teacherapp/utils/checkUpdate.dart:216:5)
E/flutter ( 1667): #5      callbackDispatcher.<anonymous closure> (package:flutter_downloader/src/callback_dispatcher.dart:24:13)
E/flutter ( 1667): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter ( 1667): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter ( 1667): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter ( 1667): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter ( 1667): #10     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 1667): #11     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 1667): #12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 1667): #13     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter ( 1667): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
E/flutter ( 1667): 
`

**Comment by shengdoushi** [comment]
I find my issue. I used third lib: flutter_downloader, and use Openfile in another isolate.

**Comment by loongwind** [comment]
Me too, how can I solve it?

**Comment by crazecoder** [comment]
I will close this issue. If this problem still exists in the latest version, please inform me and I will reopen it
