### ISSUE TITLE
Support for Flutter 1.12 + Android v2 embedding

### ISSUE THREAD

**Issue by Boehrsi** [crazecoder/open_file#79]
Right now the plugin isn't working with Flutter 1.12 + Android v2 embedding, as the used activity (https://github.com/crazecoder/open_file/blob/master/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L48) is always `null`.
It would be great if the plugin could get upgraded to support the new Android embedding, **this will be a breaking change**. A *how to* can be found at https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration. 
Most relevant is probably the implementation of the ActivityPluginBinding interface https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityPluginBinding.java.
I would also suggest to update the error handling for the startActivity call (https://github.com/crazecoder/open_file/blob/master/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java#L144), I think it should distinguish between "no app found" and general errors. I only found the specific reason for the problem via breakpoints directly within the plugin, as the `result.error` response was only "app not found", but in reality it's was a NullPointerException due to the null activity.

Btw. thanks for the efforts and the nice plugin :).

**Comment by Boehrsi** [comment]
I just discovered the repository already contains the required changes, the release version just don't. Is there a timeline for a new release with the updated code?

**Comment by crazecoder** [comment]
95fd7ee361c0331d1f0bd4987ba1a25dd8ba4177

**Comment by Boehrsi** [comment]
Thanks a lot :+1: and again, thanks for the nice plugin :).
