### ISSUE TITLE
iOS - Open File

### ISSUE THREAD

**Issue by daryll-fourie** [crazecoder/open_file#8]
Hi,

First of all, great work on the plugin! It really helped me a lot with a Flutter App I'm currently busy with.

I just have a question regarding the iOS implementation: 
I noticed that in Android, when calling `open`, it actually opens the .jpeg/.pdf in the relevant app on the device. When calling `open` on an iOS simulator, it opens a dialog from the bottom giving me the options to "Share" the file via AirDrop, ICloud Photo Sharing and also a "Save to Files" option. Is this standard behaviour?

I would expect it to just open the .jpeg/.pdf in the relevant app, just like in Android?

I haven't been able to test this on an actual iOS device yet, so it might be a simulator issue.
I just wanted to confirm this behaviour. 
Please let me know if this is how the plugin should work or am I missing something here?

Keep up the great work!

Regards,
Daryll Fourie

**Comment by crazecoder** [comment]
Yes, it is different on the simulator and on the real machine.

**Comment by daryll-fourie** [comment]
Okay, thx for the speedy response. 
I will make sure to test this on an actual device.

Regards,
Daryll Fourie

**Comment by daryll-fourie** [comment]
I just tested this on an iPhone 5s and it also opens that "Share" view.

Please see the attached screenshot:
![image](https://user-images.githubusercontent.com/40272713/45030540-83339900-b04c-11e8-9c57-dfd3c6ae346a.png)

I tested this with a .jpeg and a .pdf file.

**Comment by daryll-fourie** [comment]
Hey, do you perhaps have any feedback regarding this?

If you want, I can create a pull request and see if I can fix the issue on my side.
Let me know if I can help you out :)

I'm an Android dev actually but I don't mind working with XCode every now and then.

Regards,
Daryll

**Comment by crazecoder** [comment]
This may be a mechanism issue, and can be previewed if the third-party application is open to the public.

**Comment by daryll-fourie** [comment]
Unfortunately I cannot share the third-party application as it is a company private in-house app.

When you say a mechanism issue, what do you mean with that?
Currently, I just have a .jpeg which is saved in the `getApplicationDocumentsDirectory`, which is the default Documents directory, is that correct?

**Comment by daryll-fourie** [comment]
I just checked on my iOS testing device, the path where the file is stored is : 
**/var/mobile/Containers/Data/Application/15EB2091-D8A2-42FF-8379-B3A9CC511F73/Documents/Docs/58/doge.jpeg**

This is the Documents directory which only the app can access (https://flutter.io/cookbook/persistence/reading-writing-files/), is this maybe the problem? That the iOS open file app cannot access the image? 

Where did you store your files on the iOS device when testing this with flutter?

**Comment by rtoshmukhamedov** [comment]
The same issue on iOS. The bottom sheet is displaying options. However, I can't open any files.

Everything working on Android.

**Comment by daryll-fourie** [comment]
Hi @daniel-mf & @rtoshmukhamedov , unfortunately I haven't been able to find a solution to this problem. If I do find the problem, I will update this issue as soon as possible.

**Comment by rtoshmukhamedov** [comment]
May be UIDocumentInteractionController presentpreview should be used?

**Comment by daniel-mf** [comment]
I think instead of using `presentOpenInMenuFromRect` we should use `presentPreviewAnimated`
I just followed [this tutorial](https://code.tutsplus.com/tutorials/ios-sdk-previewing-and-opening-documents--mobile-15130) and it works like a charm.
I'm gonna give that a try.

**Comment by daryll-fourie** [comment]
That's awesome @daniel-mf , well done!
@crazecoder , if this works will you please merge it into your master branch?

**Comment by daniel-mf** [comment]
I could not manage to make it work yet, nothing happens, no error at all.

**Comment by daniel-mf** [comment]
I was able to make it work as expected (at least for the few tests I've done)
Took as example this plugin this [DocumentsPickerPlugin](https://git.uni-paderborn.de/asta/pdf_picker/blob/master/ios/Classes/DocumentsPickerPlugin.m)
I have only tested PDF files, working just fine!

**Comment by daryll-fourie** [comment]
Hi @daniel-mf , what is the latest status of you progress? I see you've made various commits to your fork, including some Android changes which you rolled back. Is the iOS part working as expected now? I will try and reference your fork locally then I can test a few other file types (other than '.pdf') from my side.

**Comment by daniel-mf** [comment]
Hey @daryll-fourie, I've tested even with zip files, all working fine on iOS!

**Comment by daryll-fourie** [comment]
@daniel-mf , thanks! I changed my reference in the pubsec.yaml and tested it successfully on Android. I do however get the following error & warning when compiling for iOS -->

<img width="1163" alt="screen shot 2018-09-19 at 10 29 09" src="https://user-images.githubusercontent.com/40272713/45741155-2eb91d80-bbf7-11e8-8147-322f6407e4bf.png">

**Comment by daryll-fourie** [comment]
@daniel-mf the above error I have might be as result of the version of my Xcode. It is Version 9.4.1 (9F2000), what is yours?

**Comment by daryll-fourie** [comment]
@daniel-mf works like a charm!! Well freaking done man! :) I tested it with the following files and it worked (on my device) : pdf, jpg & png. I'm pretty sure other file types will work too as long as the OS can handle it! Whoohooo!!! Thank you so much @daniel-mf !

@crazecoder do you perhaps want to merge his branch into yours?

**Comment by rtoshmukhamedov** [comment]
Thanks a lot @daniel-mf. It is working well.

**Comment by rtoshmukhamedov** [comment]
@crazecoder Can you merge his changes?

**Comment by crazecoder** [comment]
yeah,no problem
