### ISSUE TITLE
opening zip files on Android

### ISSUE THREAD

**Issue by blaneyneil** [crazecoder/open_file#81]
i'm using the Archive package:

https://pub.dev/packages/archive

to create a zip.  on both iOS and Android it's returning a mime type of application/zip.  when i attempt to open the the generated zip with open_file, via:

```
    await OpenFile.open(_fullPath).then((_result){
      print('success');
    }).catchError((e){
      print('open error:');
      print(e);
    });
```

it's "success" on both platforms and the catchError is never triggered.  but on iOS it actually opens the zip, while Android just silently fails w/ no further output.  

using open_file: ^3.0.1

[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)

**Comment by crazecoder** [comment]
Use result.type to determine success

**Comment by blaneyneil** [comment]
ahhh.  got, thanks.  getting `ResultType.noAppToOpen` upon:

  ```
  await OpenFile.open(_fullPath).then((OpenResult _result){
      print(_result.type);
    }).catchError((e){
      print('open error:');
      print(e);
    });
```
which of course helps things along.  it'd be really helpful to include this in the pub.dev example.  thanks for everything with this package.

**Comment by marcos930807** [comment]
> ahhh. got, thanks. getting `ResultType.noAppToOpen` upon:
> 
> ```
> await OpenFile.open(_fullPath).then((OpenResult _result){
>     print(_result.type);
>   }).catchError((e){
>     print('open error:');
>     print(e);
>   });
> ```
> 
> which of course helps things along. it'd be really helpful to include this in the pub.dev example. thanks for everything with this package.

Same think appens form me ResultType.noAppToOpen

**Comment by marcos930807** [comment]
Any news on this?

**Comment by AndroidNils** [comment]
Same Problem! This is a only android 10 problem?

**Comment by crazecoder** [comment]
I will close this issue. If this problem still exists in the latest version, please inform me and I will reopen it

**Comment by viktor-savchik-idf** [comment]
Still exists in 3.2.1 version.
