### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by CyberGhost007** [crazecoder/open_file#83]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=33432, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.workruit/com.workruit.MainActivity}: java.lang.NullPointerException

**Comment by IanChenBJ** [comment]
same issue, when alow the permission request, app crashed.

**Comment by crazecoder** [comment]
I will close this issue. If this problem still exists in the latest version, please inform me and I will reopen it
