### ISSUE TITLE
首次进行app内下载安装时，会弹出是否安装未知应用的界面，允许后再返回app就关掉了

### ISSUE THREAD

**Issue by JeremyMing** [crazecoder/open_file#89]
求助，首次进行app内下载安装时，会弹出是否安装未知应用的界面，允许后再返回app就关掉了，请问
1 是否可以跳过此步骤？
2 跳转至安装时设置Intent.FLAG_ACTIVITY_NEW_TASK 为flag而不是FLAG_ACTIVITY_SINGLE_TOP，是不是更好一些？

**Comment by crazecoder** [comment]
duplicate of https://github.com/crazecoder/open_file/issues/92
