### ISSUE TITLE
Couldn't find meta-data for provider with authority

### ISSUE THREAD

**Issue by carotkut94** [crazecoder/open_file#93]
I had a android app and i added a flutter module in it with open_file as dependency, if i run the module separately it works fine, but when i run the android app(having that module)

i get flutter exception stating
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Couldn't find meta-data for provider with authority.
and java exception stating
 java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority 

I already have read the readme file and added 
```
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            tools:replace="android:authorities"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                tools:replace="android:resource"
                android:resource="@xml/provider_paths" />
</provider>
```
into the AndroidManifest.xml of the base app in which flutter module is added. 
and tried the other way around as well, by putting this xml in the modules manifest file as well.

**Comment by S-Man42** [comment]
Same here. Are there any solutions so far?
