### ISSUE TITLE
Open torrent files or magnet links

### ISSUE THREAD

**Issue by Julitech** [crazecoder/open_file#95]
Please is there a way i can open torrent files or magnet links

**Comment by crazecoder** [comment]
d7e1c500731393bde7c8bb12f28221ceb1da0c6d It is supported on Android, Please let me know if there are any problems

**Comment by RomjanHossain** [comment]
Hey @crazecoder ! i'm having problem with opening "magnet links" ! it shows **ResultType.fileNotFound** . 

is there any way to open magnet link ?
